#!/bin/sh



# disable apport
[ -e /etc/default/apport ] && sed -i '/^enabled/s/1/0/g' /etc/default/apport 2>&1



# dconf apparmor
if ! grep -q "dconf" /etc/apparmor.d/abstractions/gnome 2>&1; then
  echo ""                   >> /etc/apparmor.d/abstractions/gnome
  echo "  # max dconf"      >> /etc/apparmor.d/abstractions/gnome
  echo "  /etc/dconf/** r," >> /etc/apparmor.d/abstractions/gnome
  invoke-rc.d apparmor reload
fi


