#!/bin/sh



# set nautilus background red color for root
# bash /usr/share/max/nautilus_background_for_root.sh


# set caja background red color for root
bash /usr/share/max/caja_background_for_root.sh || true


# change background image with better size
/usr/sbin/max-set-background 2>&1 > /dev/null
