#!/usr/bin/env bash

function overlay_file() {
    local SYSTEM_FILE="/usr/share/max-mate/settings-overlay/${1}"
    if [ -e /usr/share/max-mate/settings-overlay-infantil/${1} ]; then
        local SYSTEM_FILE="/usr/share/max-mate/settings-overlay-infantil/${1}"
    fi
    local USER_FILE="${HOME}/.${1}"
    local USER_DIR=$(dirname "${USER_FILE}")
    if [ ! -f "${USER_FILE}" ]; then
        mkdir -p "${USER_DIR}"
        cp "${SYSTEM_FILE}" "${USER_FILE}"
    fi
}

# If the 'xim' input method is set, probably by gnome-language-selector,
# this causes all manner of compatibility issues. This is a work around
# for pre-existing configurations, a patch has been submitted upstream.
#  - https://bugs.launchpad.net/language-selector/+bug/1550325
function correct_xinputrc() {
    [ ! -e ${HOME}/.xinputrc ] && return
    DETECT_XIM=$(grep xim ${HOME}/.xinputrc)
    if [ $? -eq 0 ]; then
        AUTO=$(im-config -m | sed '3q;d')
        /usr/bin/im-config -n ${AUTO}
    fi
}

PLANK_VERSION="20210227-01"
if [ -d /usr/share/max-mate/settings-overlay-infantil/config/plank/dock1/launchers ]; then
    PLANK_VERSION="${PLANK_VERSION}-infantil"
fi


if [ ! -e "${HOME}/.config/plank/dock1/.v${PLANK_VERSION}" ]; then

    rm -f ${HOME}/.config/plank/dock1/.v*
    rm -f ${HOME}/.config/plank/dock1/launchers/*

    dconf reset -f /net/launchpad/plank/ 2>&1 > /dev/null

    if [ -d /usr/share/max-mate/settings-overlay-infantil/config/plank/dock1/launchers ]; then
        LAUNCHERS="/usr/share/max-mate/settings-overlay-infantil/config/plank/dock1/launchers"
        for f in $(find "${LAUNCHERS}" -type f | sed -e 's@/usr/share/max-mate/settings-overlay-infantil/@@g'); do
            overlay_file ${f}
        done
    else
        LAUNCHERS="/usr/share/max-mate/settings-overlay/config/plank/dock1/launchers/"
        for f in $(find "${LAUNCHERS}" -type f | sed -e 's@/usr/share/max-mate/settings-overlay/@@g'); do
            overlay_file ${f}
        done
    fi

    # plank version
    touch "${HOME}/.config/plank/dock1/.v${PLANK_VERSION}"
fi

overlay_file config/folder-color/hide_donation
overlay_file config/libreoffice/4/user/registrymodifications.xcu
overlay_file config/synapse/config.json
overlay_file config/Trolltech.conf
correct_xinputrc
