#!/bin/sh

if [ -d /var/lib/homealumno/ ] && [ ! -e /var/lib/homealumno/profiles.ini ]; then
  cat << EOF > /var/lib/homealumno/profiles.ini
[alumno]
exceptions = .dmrc,
screensaver = 1
wallpaper = ""
users = alumno,
[main]
profiles = alumno,
EOF

  mkdir -p /var/lib/homealumno/profiles/alumno
fi



# remove compiz=1 line by default
if [ -e /var/lib/homealumno/.disable-compiz ] ; then
  if grep -q compiz /var/lib/homealumno/profiles.ini; then
    sed -i '/compiz/d' /var/lib/homealumno/profiles.ini
    touch /var/lib/homealumno/.disable-compiz
  fi
fi

#DEBHELPER#
