#!/bin/sh

PREREQ=""
DESCRIPTION="Configuring MaX user live HOME..."

. /scripts/casper-functions

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

log_begin_msg "$DESCRIPTION"


for file in /usr/share/max-manuales/manual.desktop /usr/share/max-manuales/install-manual.desktop; do
    if [ -f "/root/$file" ]; then
        chroot /root install -D -o $USERNAME -g $USERNAME $file /home/$USERNAME/Desktop/$(basename "$file")
    fi
done

# rename Desktop, Examples chown to max user
chroot /root << EOF
rm -rf /home/$USERNAME/Escritorio
mv /home/$USERNAME/Desktop /home/$USERNAME/Escritorio
ln -s /home/$USERNAME/Escritorio /home/$USERNAME/Desktop
chown $USERNAME:$USERNAME /home/$USERNAME/Desktop
touch /home/$USERNAME/.sudo_as_admin_successful
chown $USERNAME:$USERNAME /home/$USERNAME/.sudo_as_admin_successful
mv /home/$USERNAME/Escritorio/Examples /home/$USERNAME/Escritorio/Ejemplos
EOF


# copy Madrid timezone
cp -f /root/usr/share/zoneinfo/Europe/Madrid /root/etc/localtime


log_end_msg
