#!/bin/sh

PREREQ=""
DESCRIPTION="Configuring MaX keyboard..."

. /scripts/casper-functions

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

log_begin_msg "$DESCRIPTION"

chroot /root << EOF
sed -i '/XkbModel/s/" pc105"/"pc105"/g' /etc/X11/xorg.conf
sed -i '/XkbLayout/s/" es"/"es"/g'      /etc/X11/xorg.conf
EOF

log_end_msg
