#!/bin/sh

PREREQ=""
DESCRIPTION="Disable SCIM in MAX..."


prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

. /scripts/casper-functions

log_begin_msg "$DESCRIPTION"

if [ -e /root/usr/bin/im-switch ]; then
  chroot /root << EOF
im-switch -z all_ALL -s none
EOF

fi

log_end_msg
