#!/bin/sh

PREREQ=""
DESCRIPTION="Configure WACOM tablets in MaX..."

. /scripts/casper-functions

prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

log_begin_msg "$DESCRIPTION"

if [ -e /root/usr/sbin/max-setup-tablet ]; then
  chroot /root << EOF
/usr/sbin/max-setup-tablet /etc/X11/xorg.conf
EOF

fi

log_end_msg
