#!/bin/sh

PREREQ=""
DESCRIPTION="Fix OpenOffice.org in live mode..."


prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

# disabled
exit 0

. /scripts/casper-functions

log_begin_msg "$DESCRIPTION"

if [ -d /root/usr/lib/openoffice/program ]; then
   cat << EOF > /root/etc/rc2.d/S17fix_OOo
#!/bin/sh


case "\$1" in
  start)
    for f in \$(file /usr/lib/openoffice/program/*| awk -F":" '/ELF/{print \$1}'); do
       # delete file and create link from /rofs/
       rm -f \$f
       ln -s /rofs/\$f \$f
    done
    ;;
esac


exit 0

EOF
chmod +x /root/etc/rc2.d/S17fix_OOo


fi

log_end_msg
