#!/bin/sh

PREREQ=""
DESCRIPTION="Configuring MAX user live HOME..."


prereqs()
{
       echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
       prereqs
       exit 0
       ;;
esac

. /scripts/casper-functions

log_begin_msg "$DESCRIPTION"

# disable apport crashes
sed -i 's/enabled=1/enabled=0/' /root/etc/default/apport

# delete old ubiquity
rm -f /root/home/$USERNAME/*/ubiquity*desktop 2>/dev/null
rm -rf /root/home/$USERNAME/Desktop 2>/dev/null

chroot /root install -d -o $USERNAME -g $USERNAME /home/$USERNAME/Escritorio

for file in /usr/share/applications/ubiquity-gtkui.desktop /usr/share/max-manuales/install-manual.desktop; do
    if [ -f "/root/$file" ]; then
        chroot /root install -D -o $USERNAME -g $USERNAME $file /home/$USERNAME/Escritorio/$(basename "$file")
    fi
done

# delete from Escritorio or Desktop
rm -rf /root/home/$USERNAME/*/*examples*
rm -rf /root/home/$USERNAME/*examples*


# copy Europe/Madrid timezone
cp -f /root/usr/share/zoneinfo/Europe/Madrid /root/etc/localtime


# adduser to sambashare group
chroot /root adduser $USERNAME sambashare

if [ -e /root/etc/lxdm/lxdm-max.conf ]; then
  # configure autologin in nanomax
  # /etc/lxdm/lxdm-max.conf
  sed 's/#autologin/autologin/g' /root/etc/lxdm/lxdm-max.conf > /root/etc/lxdm/lxdm-max.conf.new
  mv /root/etc/lxdm/lxdm-max.conf.new /root/etc/lxdm/lxdm-max.conf
fi

# don't run SSH in live session
if [ -d /root/etc/ssh ]; then
  touch /root/etc/ssh/sshd_not_to_be_run
fi

# use xfce desktop if found in cmdline
if grep -q "xfce" /proc/cmdline; then
  chroot /root /usr/lib/lightdm/lightdm-set-defaults -s xfce
fi


# hack for Ubiquity and Xfce4
# ubiquity loads with black background
rm -rf /root/root/.themes

# Try to no corrupt console (MAX 10.0)
# chroot /root loadkeys es
# chroot /root setupcon --save-only

# don't run jockey in live session
rm -f /root/etc/xdg/autostart/*jockey*

cat << EOF > /root/etc/X11/Xsession.d/10-max-change-background

sudo /usr/sbin/max-set-background

EOF

# start max-mate-welcome in LIVE mode
if [ -e /root/usr/share/applications/max-mate-software.desktop ]; then
  sed -i 's/Exec=max-mate-welcome/Exec=max-mate-welcome --jump-to=hellolive/g' \
         /root/usr/share/applications/max-mate-software.desktop
fi

if [ -e /root/etc/xdg/autostart/max-mate-welcome-autostart.desktop ]; then
  sed -i 's/Exec=max-mate-welcome/Exec=max-mate-welcome --jump-to=hellolive/g' \
         /root/etc/xdg/autostart/max-mate-welcome-autostart.desktop
fi

# prevent double entries in sources.list
chroot /root find /usr/lib/ubiquity -name "*.distrib" -delete

log_end_msg
