#!/bin/bash

if [ "$1" = "amd64" ]; then
  LOCAL_MIRROR=1 MIRROR=127.0.0.1 ENABLE_EXTRA=1 AMD64=1 max-genlive 2>&1 | tee -a max-amd64.log
  exit 0
elif [ "$1" = "i386" ]; then
  LOCAL_MIRROR=1 MIRROR=127.0.0.1 ENABLE_EXTRA=1 max-genlive 2>&1 | tee -a max-i386.log
  exit 0
fi

stamp=$(date '+%Y%m%d_%H%M')
created=$(date '+%Y%m%d')


DISTRO=jammy
DISTRO_VERSION="22.04"
ARCH=i386
NANOARCH=i386
MAX_VERSION="12.5-FINAL"
MAX_VOLID="MAX_12_${created}"
IMAGE_NAME="MAX-${MAX_VERSION}"
LINUX_IMAGE="max-linux"
LINUX_HEADERS="max-linux-headers"
XSERVER_XORG="xserver-xorg"
MAXHOSTNAME=max12
INSTALL_MOODLE=no
MIRRORMAX="max.educa.madrid.org"
SYSLINUX_THEME_VERSION="max12"
REPODIR="max12"

## Create a 12.04 with trusty kernel and Xorg
#LINUX_IMAGE="linux-image-generic-lts-trusty max-linux"
#LINUX_HEADERS="linux-headers-generic-lts-trusty max-linux-headers linux-lts-trusty-tools"
#XSERVER_XORG="xserver-xorg-lts-trusty libgl1-mesa-dri-lts-trusty libgl1-mesa-glx-lts-trusty x11-xserver-utils-lts-trusty"

unset HOME
export LC_ALL=C
export LANG=C


if [ "$MIRROR" = "" ]; then
  MIRROR=127.0.0.1
fi

if [ "$AMD64" = "1" ]; then
  ARCH=amd64
fi

TITLE="MAX ${MAX_VERSION}"


if [ "$LOCAL_MIRROR" = "" ]; then
  LOCAL_MIRROR=
else
  LOCAL_MIRROR=1
fi

if [ "$ENABLE_EXTRA" = "" ]; then
  ENABLE_EXTRA=
else
  ENABLE_EXTRA=1
fi

if [ "$ENABLE_EXTRA_INFANTIL" = "" ]; then
  ENABLE_EXTRA_INFANTIL=
else
  ENABLE_EXTRA_INFANTIL=1
fi

if [ "$ENABLE_NANO" = "" ]; then
  ENABLE_NANO=
else
  ENABLE_NANO=1
fi

if [ "$ENABLE_NANOMAX_MOODLE" = "1" ]; then
  NANOMAX_MOODLE=1
else
  NANOMAX_MOODLE=0
fi

if [ "$BASE" = "" ]; then
  BASE=""
fi

CURDIR=$(pwd)

CHROOT=$CURDIR/chroot.${ARCH}
NANOCHROOT=$CURDIR/nanochroot.${ARCH}
CDRW=$CURDIR/cdimage.${ARCH}
CDINF=$CURDIR/cdinfantil
NANOMAX=$CDRW/nanomax
#MKSQUASHFS=/usr/local/bin/mksquashfs
MKSQUASHFS=/usr/bin/mksquashfs


NEW_ISOLINUX=${BASE}/usr/share/max-genlive/isolinux
GENLIVE=${BASE}/usr/share/max-genlive
PKGSDIR=${GENLIVE}/pkgs
APT_OPTS="-y --force-yes -o Dpkg::Options::=\"--force-confnew\""
# --force-yes => --allow-downgrades --allow-remove-essential --allow-change-held-packages
APT_OPTS="-y --allow-downgrades --allow-change-held-packages -o Dpkg::Options::=\"--force-confnew\""
HOOKS=${BASE}/usr/share/max-genlive/hooks/
MY_NAME=$(basename $0)



# include all package list
for f in $(find ${PKGSDIR}/ -name "*.dvdlist" -type f); do
  echo " * Include $f for repo packages"
  . ${f}
done


# include all package list *.livelist
for f in $(find ${PKGSDIR}/ -name "*.livelist" -type f); do
  echo " * Include $f for live packages"
  . ${f}
done



ayuda() {
cat << EOF
  Ayuda de max-genlive:

    max-genlive i386
    max-genlive amd64

    No hacen falta demasiadas cosas para hacer generar un livecd pero
    existen algunas variables para personalizarlo más:

    LOCAL_MIRROR=1 usará /usr/share/max-genlive/sources.list-local
                   como repositorio para hacer las descargas
                   Viene configurado como $MIRROR LOCAL_MIRROR=$LOCAL_MIRROR

    MIRROR=$MIRROR IP o nombre de equipo que se usará para el mirror

    DISABLE_SQUASHFS=1 ni comprime ni descomprime el archivo squashfs (para hacer pruebas)

    DISABLE_CLEAN=1 no borra los directorios temporales

    ENABLE_EXTRA=1 Añade a la ISO varios paquetes (ver variable PAQUETES_EXTRA)
                   Para usar esta opción tienes que ser desarrollador de max y tener cuenta
                   SSH en max.educa.madrid.org porque hay que subir el archivo Release
                   firmarlo con la clave GPG de MAX y descargar el Release.gpg

    ENABLE_EXTRA_INFANTIL=1 Crea un CDROM multiarquitectura  de complementos para
                            infantil y primaria (sólo en i386)

    ENABLE_NANO=1 Generar NanoMax y CDlive

    ONLY_NANO_CDROM=1 Generar CDROM NanoMax y salir

    ENABLE_NANOMAX_MOODLE=1 Añadir moodle a nanoMAX

    AMD64=1 Build amd64 images (default i386)

EOF
}

_exit() {
  echo "Se ha producido un error:"
  echo "--------------------------------"
  echo "$@"
  echo "--------------------------------"
  . $HOOKS/90umount
  echo "matando $MY_NAME"
  killall $MY_NAME
}

_echo() {
  echo ""
  echo " *  $@"
  echo ""
}


_revert_invoke() {
 if [ "$1" != "" ]; then
   DIR=$1
 else
   DIR=$CHROOT
 fi

 if [ -e $DIR/usr/sbin/invoke-rc.d.REAL ]; then
   _echo "Revirtiendo /usr/sbin/invoke-rc.d"
   mv $DIR/usr/sbin/invoke-rc.d.REAL $DIR/usr/sbin/invoke-rc.d
 fi
 if [ -e $DIR/sbin/start-stop-daemon.REAL ]; then
   _echo "Revirtiendo /sbin/start-stop-daemon"
   mv $DIR/sbin/start-stop-daemon.REAL $DIR/sbin/start-stop-daemon
 fi

 if chroot $DIR/ dpkg-divert --list| grep -q "/sbin/initctl"; then
   _echo "Revirtiendo /sbin/initctl"
   rm -f $DIR/sbin/initctl
   chroot $DIR dpkg-divert --local --remove /sbin/initctl
   [ -e $DIR/sbin/initctl.distrib ] && \
     mv $DIR/sbin/initctl.distrib $DIR/sbin/initctl
 fi

# if [ -e $DIR/sbin/initctl.distrib ]; then
#   rm -f $DIR/sbin/initctl
#   chroot $DIR dpkg-divert --local --remove /sbin/initctl
#   [ -e $DIR/sbin/initctl.distrib ] && \
#     mv $DIR/sbin/initctl.distrib $DIR/sbin/initctl
# fi

 if chroot $DIR/ dpkg-divert --list| grep -q "/usr/sbin/update-grub"; then
   _echo "Revirtiendo /usr/sbin/update-grub"
   rm -f $DIR/usr/sbin/update-grub
   chroot $DIR dpkg-divert --local --remove /usr/sbin/update-grub
   [ -e $DIR/usr/sbin/update-grub.distrib ] && \
     mv $DIR/usr/sbin/update-grub.distrib $DIR/usr/sbin/update-grub
 fi

# if [ -e $DIR/usr/sbin/update-grub.distrib ]; then
#   rm -f $DIR/usr/sbin/update-grub
#   chroot $DIR dpkg-divert --local --remove /usr/sbin/update-grub
#   [ -e $DIR/usr/sbin/update-grub.distrib ] && \
#     mv $DIR/usr/sbin/update-grub.distrib $DIR/usr/sbin/update-grub
# fi

 rm -f $DIR/usr/sbin/policy-rc.d
}

_add_invoke() {
 if [ "$1" != "" ]; then
   DIR=$1
 else
   DIR=$CHROOT
 fi
  if [ ! -e $DIR/usr/sbin/invoke-rc.d.REAL ]; then
    # Cambiamos invoke-rc.d
    mv $DIR/usr/sbin/invoke-rc.d $DIR/usr/sbin/invoke-rc.d.REAL
    cat << EOF > $DIR/usr/sbin/invoke-rc.d
#!/bin/sh
echo "" >&2
echo "  ** Fake invoke-rc.d called with args: '\$@'" >&2
echo "" >&2
exit 0
EOF
    chmod +x $DIR/usr/sbin/invoke-rc.d
  fi

  if [ ! -e $DIR/sbin/start-stop-daemon.REAL ]; then
    # Cambiamos start-stop-daemon
    mv $DIR/sbin/start-stop-daemon $DIR/sbin/start-stop-daemon.REAL
    cat << EOF > $DIR/sbin/start-stop-daemon
#!/bin/sh
echo "" >&2
echo "  ** Fake start-stop-daemon called with args: '\$@'" >&2
echo "" >&2
exit 0
EOF
    chmod +x $DIR/sbin/start-stop-daemon
  fi


  if [ -e $DIR/usr/sbin/policy-rc.d ]; then
cat << EOF > $DIR/usr/sbin/policy-rc.d
#!/bin/sh
echo "All runlevel operations denied by policy, args: '\$@'" >&2
exit 101
EOF
    chmod +x $DIR/usr/sbin/policy-rc.d
  fi

}


if [ "$1" = "--help" ]; then
  ayuda
  _exit ""
fi


# esto es para pruebas
#. /usr/share/max-genlive/hooks/10mountiso
#. /usr/share/max-genlive/hooks/20configurechroot
#. /usr/share/max-genlive/hooks/59addmaxpackages
#_exit 1

#. /usr/share/max-genlive/hooks/10debootstrap
#. /usr/share/max-genlive/hooks/20configurechroot
#. /usr/share/max-genlive/hooks/30upgrade
#. /usr/share/max-genlive/hooks/59zzinfantil
#_exit 1

if [ "$ONLY_NANO_CDROM" = "1" ]; then
  . ${BASE}/usr/share/max-genlive/hooks/90umount
  . ${BASE}/usr/share/max-genlive/hooks/75nanomax
  . ${BASE}/usr/share/max-genlive/hooks/90umount
  _exit "Fin de pruebas"
fi

if [ "$ONLY_ISO" = "1" ]; then
#  . ${BASE}/usr/share/max-genlive/hooks/60clean
  . ${BASE}/usr/share/max-genlive/hooks/80buildiso
  . ${BASE}/usr/share/max-genlive/hooks/90umount
  _exit "Fin ONLY_ISO"
fi


for hook in $HOOKS/*; do
  #_echo "Cargando extension $hook"
  [ -f $hook ] && . $hook || _exit "Error ejecutando $hook"
done

_echo "Terminado"

exit 0
