#!/bin/sh
#
# Configure GDM theme with gconf
#

if [ "$(which sudo)" = "" ] || [ "$(which gconftool-2)" = "" ]; then
  exit 0
fi


sudo gconftool-2 --direct --config-source xml:readwrite:/etc/gconf/gconf.xml.mandatory \
                 --type bool --set "/apps/gdm/simple-greeter/disable_user_list" "false"

sudo gconftool-2 --direct --config-source xml:readwrite:/etc/gconf/gconf.xml.mandatory \
                 --type string --set "/apps/gdm/simple-greeter/banner_message_text" ""

sudo gconftool-2 --direct --config-source xml:readwrite:/etc/gconf/gconf.xml.mandatory \
                 --type bool --set "/apps/gdm/simple-greeter/banner_message_enable" "false"

sudo gconftool-2 --direct --config-source xml:readwrite:/etc/gconf/gconf.xml.mandatory \
                 --type string --set "/apps/gdm/simple-greeter/logo_icon_name" "max"


if id gdm >/dev/null 2>&1; then
  sudo -u gdm gconftool-2 --direct --config-source xml:readwrite:/var/lib/gdm/.gconf --type string --set "/desktop/gnome/background/picture_filename" "/usr/share/images/gdm/maxgdm.png"
  sudo -u gdm gconftool-2 --direct --config-source xml:readwrite:/var/lib/gdm/.gconf --type string --set "/desktop/gnome/interface/icon_theme" "maxtoon"
  sudo -u gdm gconftool-2 --direct --config-source xml:readwrite:/var/lib/gdm/.gconf --type string --set "/desktop/gnome/interface/gtk_theme" "MaxColors"
  echo " * Configurando tema en GDM para MaX..."
else
  echo " * No se ha encontrado el usuario gdm ..."
fi


