#!/bin/sh -e

if [ "${1}" = "upgrade" ]; then
    if dpkg --compare-versions ${2} gt 0.3.5; then
	update-alternatives --remove acroread \
	/usr/lib/Adobe/Reader8/bin/acroread-en
    fi
fi

#DEBHELPER#

exit 0
