#!/bin/bash

EXTLINUX=/usr/sbin/extlinux

# ext4 in ubuntu is not supported by syslinux, use our extlinux-ext4
ROOT_DEV=$(df /boot/| awk '/dev/ {print $1}')
ROOT_FS_TYPE=$(blkid -o udev ${ROOT_DEV} | awk -F"=" '/ID_FS_TYPE=/ {print $2}')

if [ "$ROOT_FS_TYPE" = "ext4" ]; then
  if [ -x /usr/sbin/extlinux-ext4 ]; then
    EXTLINUX=/usr/sbin/extlinux-ext4
  else
    echo "/etc/grub.d/50_extlinux: ERROR ext4 is not supported as root filesystem"
    exit 0
  fi
fi



VMLINUZ=$(readlink /vmlinuz)
INITRD=$(readlink /initrd.img)

echo "Updating extlinux.conf ..." >&2

mkdir -p /boot/extlinux

cat << EOF > /boot/extlinux/extlinux.conf
default max
timeout 2
prompt 0
ontimeout max

label max
	menu label MAX
	kernel /${VMLINUZ}
	append initrd=/${INITRD} root=UUID=${GRUB_DEVICE_UUID} ro quiet splash acpi=force reboot=warn

EOF

echo "Running $EXTLINUX -i /boot/extlinux ..." >&2
$EXTLINUX -i /boot/extlinux


# check if installed ok
if dd if=${ROOT_DEV} bs=512 count=1 2>/dev/null | grep -q SYSLINUX; then
  echo "  Extlinux installed on ${ROOT_DEV}" >&2
else
  echo "  ERROR: Extlinux not found on ${ROOT_DEV}" >&2
fi
