#!/bin/sh
set -e


# delete obsolete Zentyal Captive Portal
if [ -e /etc/zentyal/stubs/captiveportal/ldap.conf.mas ]; then
  echo " * Removing /etc/zentyal/stubs/captiveportal/ldap.conf.mas ..."
  rm -f /etc/zentyal/stubs/captiveportal/ldap.conf.mas
fi

[ -e /etc/zentyal/stubs/captiveportal ] && rmdir /etc/zentyal/stubs/captiveportal || true
[ -e /etc/zentyal/stubs ] && rmdir /etc/zentyal/stubs || true




#DEBHELPER#

exit 0



