#!/bin/sh
set -e

# Move a conffile without triggering a dpkg question
mv_conffile() {
    local OLDCONFFILE="$1"
    local NEWCONFFILE="$2"

    [ -e "$OLDCONFFILE" ] || return 0

    echo "Preserving user changes to $NEWCONFFILE ..."
    mv -f "$NEWCONFFILE" "$NEWCONFFILE".dpkg-new
    mv -f "$OLDCONFFILE" "$NEWCONFFILE"
}

case "$1" in
configure)
    if dpkg --compare-versions "$2" le "0.9~rc2-0ubuntu1"; then
        mv_conffile /etc/firefox-3.0/pref/ubufox.js /etc/xul-ext/ubufox.js
    fi
esac

#DEBHELPER#
