#!/bin/sh
set -e

# Prepare to move a conffile without triggering a dpkg question
prep_mv_conffile() {
    local PKGNAME="$1"
    local CONFFILE="$2"

    [ -e "$CONFFILE" ] || return 0

    local md5sum="$(md5sum $CONFFILE | sed -e 's/ .*//')"
    local old_md5sum="$(dpkg-query -W -f='${Conffiles}' $PKGNAME | \
            sed -n -e "\' $CONFFILE ' { s/ obsolete$//; s/.* //; p }")"
    if [ "$md5sum" = "$old_md5sum" ]; then
        rm -f "$CONFFILE"
    fi
}

case "$1" in
install|upgrade)
    if test -d /usr/lib/firefox/extensions/ubufox@ubuntu.com; then
        rm -rf /usr/lib/firefox/extensions/ubufox@ubuntu.com
    fi

    if test -d /usr/lib/firefox-addons/extensions/ubufox@ubuntu.com; then
        rm -rf /usr/lib/firefox-addons/extensions/ubufox@ubuntu.com
    fi

    if dpkg --compare-versions "$2" le "0.9~rc2-0ubuntu1"; then
        prep_mv_conffile ubufox /etc/firefox-3.0/pref/ubufox.js
    fi
esac

#DEBHELPER#
