#!/bin/sh


case "$1" in
    configure)

        update-alternatives \
                --install /usr/share/plymouth/themes/default.plymouth default.plymouth \
                /usr/share/plymouth/themes/max-logo/max-logo.plymouth 200
        update-alternatives \
                --install /usr/share/plymouth/themes/text.plymouth text.plymouth \
                /usr/share/plymouth/themes/max-text/max-text.plymouth 200

        if which update-initramfs >/dev/null 2>&1
        then
            update-initramfs -u
        fi
        ;;

    abort-upgrade|abort-deconfigure|abort-remove)
        ;;

    *)
        echo "$0 called with unknown argument \`$1'" 1>&2
        exit 1
        ;;
esac


#DEBHELPER#

exit 0
