#!/bin/sh

if [ "$1" = "remove" ]; then
    dpkg-divert --package plymouth-max --rename --remove /lib/plymouth/text.so.ubuntu || true
fi



case "$1" in
    remove)
        update-alternatives \
                --remove default.plymouth /lib/plymouth/themes/max-logo/max-logo.plymouth

        if which update-initramfs >/dev/null 2>&1
        then
            update-initramfs -u
        fi
        ;;

    purge)
        ;;

    upgrade|failed-upgrade|disappear)
        ;;

    abort-install|abort-upgrade)
        ;;

    *)
        echo "$0 called with unknown argument \`$1'" 1>&2
        exit 1
        ;;
esac

#DEBHELPER#

exit 0
