#!/bin/sh
set -e

if [ "x$1" = xremove ]; then
        update-alternatives \
                --remove default.plymouth /usr/share/plymouth/themes/max-logo/max-logo.plymouth
        update-alternatives \
                --remove text.plymouth /usr/share/plymouth/themes/max-text/max-text.plymouth

fi

