build/arduino/hardware             usr/share/arduino/
build/arduino/libraries            usr/share/arduino/
build/arduino/tools                usr/share/arduino/
build/arduino/revisions.txt        usr/share/arduino/

build/arduino/java                 usr/share/arduino/
build/arduino/lib                  usr/share/arduino/
build/arduino/tools-builder        usr/share/arduino/

build/arduino/arduino-builder      usr/share/arduino/
