#!/bin/sh

set -e


case "$1" in
    remove)
        # Remove bin ollama file.
         unopkg remove --shared org.extension.sample || true
	 # Remove plugin extension file.
	 if [ -e /opt/max-localwriter.oxt ]; then rm -f /opt/max-localwriter.oxt ; fi
        ;;
    purge)
	# Use it for config files.
        ;;
    upgrade)
        # This is usually handled by the postinst script for the new version.
        # For example, to do something with old-postrm.
        # old-postrm upgrade new-version
        ;;
    *)
        # Handle other cases if necessary, though this is less common.
        # For example, a deconfigured package might still have a postrm
        # called by a different package.
        ;;
esac

exit 0

