#!/bin/sh



case "$1" in
    remove|purge)

	# delete MaX start-here
	update-alternatives --remove start-here.svg /usr/share/icons/maxtoon/scalable/places/max.svg 

	# update-grub
	if [ -x "`which update-grub2 2>/dev/null`" ] && [ -e /boot/grub/grub.cfg ]; then
	   update-grub2
	fi

	;;
    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        exit 0
	;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1

esac


#DEBHELPER#

exit 0
