#!/bin/sh
# Test for linux distributions.
set -e

. /usr/share/os-prober/common.sh

partition="$1"
dir="$2"
type="$3"

if [ -f $dir/boot/grub/menu.lst ]; then
  first_entry=$(grep ^title $dir/boot/grub/menu.lst | grep kernel | head -1 | sed 's/title//g' | sed 's|\t||g')
  if [ "$(echo $first_entry | grep -c -i max)" != "0" ]; then
    # is MaX example: (MaX 3.1, kernel 2.6.22-14-generic)
    short=$(echo $first_entry| awk -F"," '{print $1}')
    long=$first_entry
    label=$(count_next_label $short)
    result "$partition:$short:$label:linux"
    #result "$partition:$long:$label:linux"
    exit 0
  fi
fi

if [ -f $dir/boot/grub/grub.cfg ]; then
  first_entry=$(grep ^menuentry $dir/boot/grub/grub.cfg | head -1 | awk -F'"' '{print $2}')
  if [ "$(echo $first_entry | grep -c -i max)" != "0" ]; then
    # is MaX example: (MaX 6.0, with Linux 2.6.32-15-generic)
    short=$(echo $first_entry| awk -F"," '{print $1}')
    long=$first_entry
    label=$(count_next_label $short)
    result "$partition:$short:$label:linux"
    #result "$partition:$long:$label:linux"
    exit 0
  fi
fi

exit 1

