#!/bin/bash
set -e

if [ -e /var/lib/max/background-selected ]; then
  exit 0
fi



RES=$(xrandr | grep '*' | head -1 | awk '{ print $1 }' 2>/dev/null)
X=${RES%x*}
Y=${RES#*x}
REL=$(($X*10/$Y))

case 1 in
$(( $REL <= 15)) ) SUFIX= "1900x1200";;
$(( $REL <= 13)) ) SUFIX= "1600x1200";;
*) SUFFIX="1920x1080";;
esac



cd /usr/share/backgrounds

rm max.png
ln -s "max-madrid-linux-${SUFFIX}.png" max.png

rm max-infantil.png
ln -s "max-madrid-linux-infantil-${SUFFIX}.png" max-infantil.png


mkdir -p /var/lib/max/
touch /var/lib/max/background-selected
