#!/bin/sh
#
# called from /etc/apt/apt.conf.d/92update-dpsyco-skel
#

echo "Procesando disparadores para max ..."


if [ -x /usr/share/gnome-menus/update-gnome-menus-cache ]; then
  # this breaks Smart PDI install script WTF !!!!
  #LC_ALL=C /usr/share/gnome-menus/update-gnome-menus-cache /usr/share/applications > /usr/share/applications/desktop.C.cache
  rm -f /usr/share/applications/desktop.C.cache
  LC_ALL=es_ES.UTF-8 /usr/share/gnome-menus/update-gnome-menus-cache /usr/share/applications > /usr/share/applications/desktop.es_ES.utf8.cache
fi

UPDATE_GRUB=0

if [ -e /etc/default/grub ]; then
  if ! grep -q "MaX" /etc/default/grub 2>/dev/null; then
    echo '' >> /etc/default/grub
    echo 'GRUB_DISTRIBUTOR="MaX-7.0"' >> /etc/default/grub
    UPDATE_GRUB=1
  fi

  if grep -q "^GRUB_HIDDEN" /etc/default/grub 2>/dev/null; then
    sed -i -e 's/^GRUB_HIDDEN/#GRUB_HIDDEN/g' /etc/default/grub
    UPDATE_GRUB=1
  fi

  if [ "$UPDATE_GRUB" = "1" ]; then
    if [ -x "`which update-grub 2>/dev/null`" ] && [ -e /boot/grub/grub.cfg ]; then
      update-grub
    fi
  fi
fi # end of [ -e /etc/default/grub ]

test -e /boot/grub/grub.cfg && sed -i '/submenu/s/Previous Linux versions/Versiones anteriores/g' /boot/grub/grub.cfg

# disable dnsmasq cache
if grep -q ^dns /etc/NetworkManager/NetworkManager.conf 2>&1; then
    echo " * Desactivando cache DNS (dnsmasq)"
    sed -i 's/dns=/#dns=/g' /etc/NetworkManager/NetworkManager.conf
fi




# force to not dist upgrades
if [ -f /etc/update-manager/release-upgrades ]; then
  if ! grep -q "^Prompt=never" /etc/update-manager/release-upgrades 2>/dev/null; then
    echo " * Desactivando actualizaciones a nuevas versiones ..."
    sed -i -s 's/Prompt=.*/Prompt=never/g' /etc/update-manager/release-upgrades
  fi
fi


# delete dropbear hook
if [ -f /usr/share/initramfs-tools/hooks/dropbear ]; then
  rm -f /usr/share/initramfs-tools/hooks/dropbear
  [ -x /usr/sbin/update-initramfs ] && update-initramfs -u
fi


# configure SSH to not allow danger logins
if [ -f /etc/ssh/sshd_config ]; then
  if ! grep -q "# MAX" /etc/ssh/sshd_config ; then
    cat << EOF >> /etc/ssh/sshd_config

# ******** no borrar este comentario ******
# MAX
# deshabilitar contraseñas conocidas
# para activar el login cambiar la contraseña
# del usuario que se quiera habilitar y eliminar
# su nombre de la siguiente línea
#
#
DenyUsers madrid alumno profesor
EOF
  # restart ssh service
  restart ssh || true
  fi
fi



if [ -d /usr/lib/jvm/ ] && [ -e /usr/share/descartes/DescartesLib.jar ]; then
  # link descartes in every JAVA package
  JVMS=$(find /usr/lib/jvm/ -maxdepth 1 -mindepth 1 -type d | grep -v jmf)
  for jvm in $JVMS; do
    if [ -d ${jvm}/jre/lib/ext/ ] && [ ! -e ${jvm}/jre/lib/ext/DescartesLib.jar ]; then
      ln -s /usr/share/descartes/DescartesLib.jar ${jvm}/jre/lib/ext/
    fi
  done
fi

if [ -x /usr/bin/xdg-mime ] && [ -e /etc/gnome/defaults.list ]; then
  # chech exe-learning mime
  if [ "$(xdg-mime query default application/x-exe-learning 2>/dev/null)" = "" ]; then
    echo "application/x-exe-learning=exe.desktop" >> /etc/gnome/defaults.list
  fi
fi


## update Firefox defaults
#FF_DIR=$(dirname /usr/lib/firefox*/firefox)
#FF_DEF=/usr/share/max-firefox-conf/profile/
#if [ ! -e "$FF_DIR/defaults/profile/localstore.rdf" ]; then
#  echo " * Actualizando perfil de Firefox $FF_DIR"
#  mkdir -p "$FF_DIR/defaults/profile/"
#  cp $FF_DEF/* "$FF_DIR/defaults/profile/"
#fi
#
## clean OLD firefox
#for f in $(echo /usr/lib/firefox*/defaults 2>/dev/null); do
#  [ ! -d "$f" ] && continue
#  [ -e "$f/../firefox" ] && continue
#  echo " * Limpiando versiones viejas de Firefox $f"
#  rm -rf "$f"
#done
#
#rmdir /usr/lib/firefox* 2>/dev/null


# disable apport
sed -i '/^enabled/s/1/0/g' /etc/default/apport 2>&1
