#!/bin/sh
#
# called from /etc/apt/apt.conf.d/92update-dpsyco-skel
#

echo "Procesando disparadores para max ..."


if [ -x /usr/share/gnome-menus/update-gnome-menus-cache ]; then
  # this breaks Smart PDI install script WTF !!!!
  #LC_ALL=C /usr/share/gnome-menus/update-gnome-menus-cache /usr/share/applications > /usr/share/applications/desktop.C.cache
  rm -f /usr/share/applications/desktop.C.cache
  LC_ALL=es_ES.UTF-8 /usr/share/gnome-menus/update-gnome-menus-cache /usr/share/applications > /usr/share/applications/desktop.es_ES.utf8.cache
fi

UPDATE_GRUB=0

if [ -e /etc/default/grub ]; then
  if ! grep -q "MaX-7.5" /etc/default/grub 2>/dev/null; then
    echo '' >> /etc/default/grub
    echo 'GRUB_DISTRIBUTOR="MaX-7.5"' >> /etc/default/grub
    UPDATE_GRUB=1
  fi

  if grep -q "^GRUB_HIDDEN" /etc/default/grub 2>/dev/null; then
    sed -i -e 's/^GRUB_HIDDEN/#GRUB_HIDDEN/g' /etc/default/grub
    UPDATE_GRUB=1
  fi

  if [ "$UPDATE_GRUB" = "1" ]; then
    if [ -x "`which update-grub 2>/dev/null`" ] && [ -e /boot/grub/grub.cfg ]; then
      update-grub
    fi
  fi
fi # end of [ -e /etc/default/grub ]

test -e /boot/grub/grub.cfg && sed -i '/submenu/s/Previous Linux versions/Versiones anteriores/g' /boot/grub/grub.cfg

# disable dnsmasq cache
if grep -q ^dns /etc/NetworkManager/NetworkManager.conf 2>&1; then
    echo " * Desactivando cache DNS (dnsmasq)"
    sed -i 's/dns=/#dns=/g' /etc/NetworkManager/NetworkManager.conf
fi




# force to not dist upgrades
if [ -f /etc/update-manager/release-upgrades ]; then
  if ! grep -q "^Prompt=never" /etc/update-manager/release-upgrades 2>/dev/null; then
    echo " * Desactivando actualizaciones a nuevas versiones ..."
    sed -i -s 's/Prompt=.*/Prompt=never/g' /etc/update-manager/release-upgrades
  fi
fi


# delete dropbear hook
if [ -f /usr/share/initramfs-tools/hooks/dropbear ]; then
  rm -f /usr/share/initramfs-tools/hooks/dropbear
  [ -x /usr/sbin/update-initramfs ] && update-initramfs -u
fi


# configure SSH to not allow danger logins
if [ -f /etc/ssh/sshd_config ]; then
  if ! grep -q "# MAX" /etc/ssh/sshd_config ; then
    cat << EOF >> /etc/ssh/sshd_config

# ******** no borrar este comentario ******
# MAX
# deshabilitar contraseñas conocidas
# para activar el login cambiar la contraseña
# del usuario que se quiera habilitar y eliminar
# su nombre de la siguiente línea
#
#
DenyUsers madrid alumno profesor
EOF
  # restart ssh service
  restart ssh || true
  fi
fi



if [ -d /usr/lib/jvm/ ] && [ -e /usr/share/descartes/DescartesLib.jar ]; then
  # link descartes in every JAVA package
  JVMS=$(find /usr/lib/jvm/ -maxdepth 1 -mindepth 1 -type d | grep -v jmf)
  for jvm in $JVMS; do
    if [ -d ${jvm}/jre/lib/ext/ ] && [ ! -e ${jvm}/jre/lib/ext/DescartesLib.jar ]; then
      ln -s /usr/share/descartes/DescartesLib.jar ${jvm}/jre/lib/ext/
    fi
  done
fi

if [ -x /usr/bin/xdg-mime ] && [ -e /etc/gnome/defaults.list ]; then
  # chech exe-learning mime
  if [ "$(xdg-mime query default application/x-exe-learning 2>/dev/null)" = "" ]; then
    echo "application/x-exe-learning=exe.desktop" >> /etc/gnome/defaults.list
  fi


  if xdg-mime query default x-scheme-handler/apt| grep -q software-center; then
    xdg-mime default apturl.desktop x-scheme-handler/apt
    sed -i '/ubuntu-software-center/d' /etc/gnome/defaults.list
    echo "x-scheme-handler/apt=apturl.desktop" >> /etc/gnome/defaults.list
  fi
fi


# apturl for firefox
if [ -d /etc/firefox/pref ]; then
  # link pref in install dir
  for f in /etc/firefox/pref/*; do
    fname=$(basename $f)
    if [ ! -e "/usr/lib/firefox/defaults/pref/$fname" ]; then
      #echo ln -s $f /usr/lib/firefox/defaults/pref/$fname
      ln -s "$f" "/usr/lib/firefox/defaults/pref/$fname"
    fi
  done
fi



# disable apport
sed -i '/^enabled/s/1/0/g' /etc/default/apport 2>&1


# set nautilus background red color for root
bash /usr/share/max/nautilus_background_for_root.sh


# dconf apparmor
if ! grep -q "dconf" /etc/apparmor.d/abstractions/gnome 2>&1; then
  echo ""                   >> /etc/apparmor.d/abstractions/gnome
  echo "  # max dconf"      >> /etc/apparmor.d/abstractions/gnome
  echo "  /etc/dconf/** r," >> /etc/apparmor.d/abstractions/gnome
  invoke-rc.d apparmor reload
fi



# TCOS lightdm support
#session optional        pam_lastlog.so silent
if [ -f /etc/pam.d/lightdm ]; then
  grep -q "pam_lastlog" /etc/pam.d/lightdm || cat << EOF >> /etc/pam.d/lightdm

# TCOS lightdm support
session optional        pam_lastlog.so silent

EOF
fi



# upgrade to MAX 7.5
if ! grep -q "/max75" /etc/apt/sources.list; then
  echo " * Updating sources.list to upgrade to MAX 7.5 ..."
  # substitutes max70 with max75
  cp /etc/apt/sources.list /etc/apt/sources.list.bak
  sed -i -e 's#http://\(.*\)/max70#http://$1/max75#g' /etc/apt/sources.list
fi


# change background image with better size
/usr/sbin/max-set-background 2>&1 > /dev/null

# ensure ligthdm is configured
if [ ! -e /etc/lightdm/lightdm.conf-max ] && [ -e /usr/lib/lightdm/lightdm-set-defaults ]; then
  /usr/lib/lightdm/lightdm-set-defaults --allow-guest false
  /usr/lib/lightdm/lightdm-set-defaults --session "gnome-classic"
  /usr/lib/lightdm/lightdm-set-defaults --greeter "unity-greeter"
  touch /etc/lightdm/lightdm.conf-max
fi

# Disable HWE https://wiki.ubuntu.com/HweStackEolNotifications
if [ ! -e /var/lib/update-notifier/disable-hwe-eol-messages ]; then
  mkdir -p /var/lib/update-notifier
  touch /var/lib/update-notifier/disable-hwe-eol-messages
fi


# add alumno to dialout
groups alumno | grep -q dialout || adduser alumno dialout

