#!/bin/bash
set -e

if [ -e /var/lib/max/background-selected ]; then
  exit 0
fi

if [ "$DISPLAY" = "" ]; then
  exit
fi

RES=$(xrandr | grep '*' | head -1 | awk '{ print $1 }' 2>/dev/null)
X=${RES%x*}
Y=${RES#*x}
REL=$(($X*10/$Y))


if [ $REL -lt 13 ]; then
  SUFIX= "1600x1200"
if [  $REL -lt 15 ]; then
  SUFIX= "1900x1200"
else
  SUFFIX="1920x1080"
fi

#case 1 in
#$(( $REL <= 15)) ) SUFIX= "1900x1200";;
#$(( $REL <= 13)) ) SUFIX= "1600x1200";;
#*) SUFFIX="1920x1080";;
#esac

if [ "$SUFFIX" = "" ]; then
  exit
fi

cd /usr/share/backgrounds

rm max.png
ln -s "max-madrid-linux-${SUFFIX}.png" max.png

rm max-infantil.png
ln -s "max-madrid-linux-infantil-${SUFFIX}.png" max-infantil.png


mkdir -p /var/lib/max/
touch /var/lib/max/background-selected
echo "${SUFFIX}" > /var/lib/max/background-selected
