#!/bin/bash


case "$1" in
purge)

  JAVAS=$(update-alternatives --list java| grep -e "jre*.sun" -e "java.*sun" | sed 's|/bin/java||g')

  for JAVA in $JAVAS; do
    EXT_DIR=$(dirname $JAVA)/ext
    if [ -d $EXT_DIR ]; then
      if [ -e $EXT_DIR/mysql-connector-java.jar ]; then
		rm -f $EXT_DIR/mysql-connector-java.jar
		echo "removing mysql-connector-java at $EXT_DIR"
      fi
    fi
  done
  ;;
esac

