#!/bin/bash

if [ "$1" = "configure" ]; then
  rm -rf /etc/skel/.config/dconf
  update-gconf-defaults || true
  glib-compile-schemas /usr/share/glib-2.0/schemas/ || true



  for home in $(find /home/ -maxdepth 1 -mindepth 1 -type d); do
    username=$(basename $home)
    cp /etc/skel/Escritorio/firefox.desktop $home/Escritorio/
    chown -R $username $home/Escritorio/firefox.desktop || true
  done


fi

#DEBHELPER#

exit 0


