#!/bin/bash

if [ "$1" = "configure" ]; then
  rm -rf /etc/skel/.config/dconf
  update-gconf-defaults || true
  glib-compile-schemas /usr/share/glib-2.0/schemas/ || true
fi

# ugly hack
# dconf don't allow to set gnome-panel
# http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=648009
#
for u in $(ls /home/*/.config/dconf/user 2>/dev/null); do
  if [ ! -e "${u}.imported" ]; then
    cat /etc/skel/.config/dconf/user > "$u"
    touch "${u}.imported"
  fi
done

#DEBHELPER#

exit 0


