#!/usr/bin/env python

import os
import time
import shutil
import threading
import commands
import tempfile
import random
from SimpleHTTPServer import SimpleHTTPRequestHandler
from BaseHTTPServer import HTTPServer

if os.path.exists('/usr/share/blockscad/'):
    os.chdir('/usr/share/blockscad/')

PORT = random.randint(25000, 26000)

server = HTTPServer(('', PORT), SimpleHTTPRequestHandler)
thread = threading.Thread(target = server.serve_forever)
thread.daemon = True
try:
    thread.start()
    print "Web thread running at 9005"
except KeyboardInterrupt:
    server.shutdown()
    sys.exit(0)

print 'OK'
time.sleep(1)
print "Starting browser..."
dname = tempfile.mkdtemp()
# status, output = commands.getstatusoutput("chromium-browser --app=http://localhost:9005")
# status, output = commands.getstatusoutput("firefox -P app -new-instance http://localhost:9005")
# status, output = commands.getstatusoutput("firefox --chrome http://localhost:9005")
status, output = commands.getstatusoutput("firefox -profile %s -no-remote -new-instance http://localhost:%s" % (dname, PORT))
print "Shutdown, removing %s" % dname
server.shutdown()
shutil.rmtree(dname)
time.sleep(1)
