#!/bin/bash -e

. /usr/share/debconf/confmodule

CONFIGFILE=/etc/max-bitten-slave

if [ ! -e $CONFIGFILE ]; then
	echo "[authentication]" > $CONFIGFILE
	echo "username =" >> $CONFIGFILE
	echo "password =" >> $CONFIGFILE
fi

db_get max-bitten-slave/username
USERNAME="$RET"
db_get max-bitten-slave/password
PASSWORD="$RET"
cp -a -f $CONFIGFILE $CONFIGFILE.tmp

test -z "$USERNAME" || grep -Eq "^ *username *=" $CONFIGFILE || echo "username =" >> $CONFIGFILE
test -z "$PASSWORD" || grep -Eq "^ *password *=" $CONFIGFILE || echo "password =" >> $CONFIGFILE

sed -e "s/^ *username\ *=.*/username\ =\ $USERNAME/" -e "s/^ *password\ *=.*/password\ =\ $PASSWORD/" < $CONFIGFILE > $CONFIGFILE.tmp
mv -f $CONFIGFILE.tmp $CONFIGFILE
chmod 600 $CONFIGFILE

set +e

if which update-python-modules >/dev/null 2>&1; then
	update-python-modules  max-bitten-slave
fi

if [ -x "/etc/init.d/max-bitten-slave" ]; then
	update-rc.d max-bitten-slave start 99 2 3 4 5 . stop 40 0 1 6 . >/dev/null
	if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
		invoke-rc.d max-bitten-slave start || exit $?
	else
		/etc/init.d/max-bitten-slave start || exit $?
	fi
fi
