#! /bin/sh
#set -e

if [ -e /tmp/max_desktop_type ]; then
  # gnome or xfce
  # tune /etc/skel/.dmrc and users .dmrc
  if [ "$(cat /tmp/max_desktop_type)" = "xfce" ]; then
    echo " * Setting XFCE desktop by default" >&2
    chroot /target /usr/lib/lightdm/lightdm-set-defaults -s xfce
    # set AccountsService
    test -d /target/var/lib/AccountsService/users/ || mkdir -p /target/var/lib/AccountsService/users/
    cat << EOF > /target/var/lib/AccountsService/users/madrid

[User]
XSession=xfce
XKeyboardLayouts=
EOF
  cat /target/var/lib/AccountsService/users/madrid > /target/var/lib/AccountsService/users/alumno
  cat /target/var/lib/AccountsService/users/madrid > /target/var/lib/AccountsService/users/profesor
  fi
fi

ARGS="i915.modeset=0 acpi_osi=Linux acpi_backlight=vendor"

# IBM hack, trac #417
if grep -q "$ARGS" /proc/cmdline; then
  echo " * Setting IBM hacks in GRUB" >&2
  if ! grep -q "$ARGS" /target/etc/default/grub 2>/dev/null; then
    . /target/etc/default/grub
    echo "# this will fix IBM issues in MAX" >> /target/etc/default/grub
    echo "GRUB_CMDLINE_LINUX=\"$GRUB_CMDLINE_LINUX $ARGS \"" >> /target/etc/default/grub
    #chroot /target update-grub
  fi
fi

chroot /target /usr/lib/lightdm/lightdm-set-defaults --allow-guest=false
chroot /target loadkeys es
chroot /target setupcon --save-only


exit 0
