#!/bin/sh
#

WEB2BOARD="/usr/share/bitbloq-offline/resources/app/app/res/web2board"

# for x64
F=${WEB2BOARD}/linux/web2boardLauncher.distrib

# for x86
if [ -e ${WEB2BOARD}/linux32/web2boardLauncher.distrib ]; then
  F=${WEB2BOARD}/linux32/web2boardLauncher.distrib
fi

gksudo "$F $@"

