#!/bin/sh
#

F=/usr/share/bitbloq-offline/resources/app/app/res/web2board/linux/web2boardLauncher.distrib
if [ -e /usr/share/bitbloq-offline/resources/app/app/res/web2board/linux32/web2boardLauncher.distrib ]; then
 F=/usr/share/bitbloq-offline/resources/app/app/res/web2board/linux32/web2boardLauncher.distrib
fi

gksudo "$F"

