#!/bin/bash

EXAMEN_ACTIVO=$(wmctrl  -l | grep  "Aulas\ Virtuales\ \|\ EducaMadrid" | awk '{ print $1 }')
TESTIGO=${HOME}/.extemp
TARGET_URL=https://www.educa2.madrid.org/educamadrid/aula-virtual
echo "se lanza el examen"
chromium --app="${TARGET_URL}" &
comprobador=0

while [ $comprobador -eq 0 ] 
do
	echo "aun no arranco"
	comprobador=$(wmctrl  -l | grep  "Aulas\ Virtuales\ \|\ EducaMadrid" | awk '{ print $1 }' |wc -l)
done

 
	while true 
	do
		echo "se activa el sentinela de navegadores"
		cat  "${TESTIGO}"

		for k in $( wmctrl  -l | grep  "Mozilla\|Chromium\|Chrome\|Opera" | awk '{ print $1 }' ) 
		do wmctrl -ic "$k"; done ; 


		echo "se comprueba que el aula examen siga activo"
		EXAMEN_ACTIVO=$( wmctrl  -l | grep  "Aulas\ Virtuales\ \|\ EducaMadrid" | awk '{ print $1 }' )

		echo "Se si Examen_activo ha cerrado se mata el proceso."
		if [ "${EXAMEN_ACTIVO}" == "" ]; then    

			kill -9 "$( cat "${TESTIGO}" )" || echo " error  al matar proceso kill -9 ${TESTIGO} "
			echo "Proceso terminado."
			exit 0
		fi
		sleep 1
    
	done & echo $!  > "${TESTIGO}"
