if [ ! -f /usr/share/max-examen-av/desactivar ] ; then
   #/usr/bin/mate-terminal &

   #cp -f /usr/share/max-examen-av/user /home/examen/.config/dconf/
   #chown examen:examen /home/examen/.config/dconf/user
   #chmod 664 /home/examen/.config/dconf/user

   /usr/bin/marco &

   #/usr/bin/galculator &

   # Restaura el perfil de Firefox.
   rm -rf /home/examen/.mozilla
   tar xzpvf /usr/share/max-examen-av/mozilla.tar.gz -C /home/examen/
   # Para crear el fichero 'mozilla.tar.gz' ejecutar como root desde '/home/examen'
   # el comando: tar czpvf /usr/share/max-examen-av/mozilla.tar.gz .mozilla/


   zenity --info --text "\
Va a entrar en un entorno gráficamente limitado.\n\
Recuerde las siguientes combinaciones de teclas:\n\n\
Ctrl+Q = Cerrar el navegador y salir de la sesión\n\
Ctrl+F5 = Recargar la página del navegador\n\n\
Alt+Flecha Izquierda = Página anterior\n\
Alt+Flecha derecha = Página siguiente"

   exec /usr/bin/firefox --kiosk https://examen.educa.madrid.org

   # exec /usr/bin/mate-session -a /usr/share/max-examen-av/mate
fi