#!/bin/bash

ODIR="${HOME}/.openroberta"
mkdir -p ${ODIR}
DBLOGFILE="${ODIR}/ora-db.log"
SERVERLOGFILE="${ODIR}/ora-server.log"

cd /usr/share/openroberta

echo 'have a look whether a database update is needed'
java -cp lib/\* de.fhg.iais.roberta.main.ServerStarter -d database.parentdir=. -d database.mode=embedded --check-for-db-updates >>$SERVERLOGFILE 2>&1

echo 'start the database server and the openroberta server as separate processes'
serverVersion=$(java -cp lib/\* de.fhg.iais.roberta.main.ServerStarter -v)
database=${ODIR}/db-${serverVersion}/openroberta-db

echo "the database server will use database directory $database"
java -cp lib/\* org.hsqldb.Server --database.0 file:$database --dbname.0 openroberta-db \$* >>$DBLOGFILE 2>&1 &
sleep 5


java -cp lib/\* de.fhg.iais.roberta.main.ServerStarter -d database.parentdir=. -d database.mode=server \$* >>$SERVERLOGFILE 2>&1 &
