#! /bin/sh

set -e


case "$1" in
       purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
       /usr/sbin/update-dpsyco-skel
        ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 0

esac

exit 0

