#!/bin/sh

#set -e

case "$1" in
    configure)

    # Update DNI-e certificates if exists
    [ -e /var/lib/dpkg/info/dnie-support.postinst ] && bash /var/lib/dpkg/info/dnie-support.postinst || true

    ;;

esac


#DEBHELPER#

exit 0


