#!/bin/sh


case "$1" in
    configure)

    # remove LC_ALL=es_ES.UTF-8
    if grep -q LC_ALL /etc/default/locale; then
        grep ^LANG /etc/default/locale > /etc/default/locale.new
        mv /etc/default/locale.new /etc/default/locale
    fi

    ;;

esac


#DEBHELPER#

exit 0
