#!/bin/sh

set -e

. /usr/share/debconf/confmodule

# previously : FP9_plugin_beta_112006.tar.gz
# currently  : install_flash_player_9_linux.tar.gz

db_get flashplugin-nonfree/local
echo "93b7c48eaa492237b807a3ae1de65cf9  $RET/install_flash_player_9_linux.tar.gz" \
| md5sum -c > /dev/null 2>&1 \
|| db_set flashplugin-nonfree/local /var/cache/flashplugin-nonfree

db_get flashplugin-nonfree/local
echo "93b7c48eaa492237b807a3ae1de65cf9  $RET/install_flash_player_9_linux.tar.gz" \
| md5sum -c > /dev/null 2>&1 \
|| db_set flashplugin-nonfree/local /usr/lib/flashplugin-nonfree-unpackdir

db_get flashplugin-nonfree/local
echo "93b7c48eaa492237b807a3ae1de65cf9  $RET/install_flash_player_9_linux.tar.gz" \
| md5sum -c > /dev/null 2>&1 \
|| db_reset flashplugin-nonfree/local 

while true; do
    db_input medium flashplugin-nonfree/local || true
    db_go
    db_get flashplugin-nonfree/local
    if [ -d "$RET" -a -f "$RET"/install_flash_player_9_linux.tar.gz ]; then
		LOCAL="true"
		break;
    elif [ "x$RET" = "x" ]; then
		break;
    fi
    db_reset flashplugin-nonfree/not_exist || true
    db_reset flashplugin-nonfree/local || true
    db_text medium flashplugin-nonfree/not_exist || true
    db_go
done

if [ "$LOCAL" != "true" ]; then
    db_reset flashplugin-nonfree/httpget
    db_input medium flashplugin-nonfree/httpget || true
    db_go
    db_get flashplugin-nonfree/httpget
fi
