#!/bin/bash
### BEGIN INIT INFO
# Provides:          max-multiseat
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      
# Short-Description: Start max-multiseat devices
### END INIT INFO

. /lib/lsb/init-functions



case "$1" in
start)
        log_begin_msg "Starting Multiseat" "max-multiseat"
          /usr/bin/start-multiseat >> /tmp/start-multiseat.log 2>&1
        log_end_msg 0
        ;;
esac



exit 0

