#!/bin/sh

# obsolete file
[ -f /etc/cron.d/max-multiseat ] && rm -f /etc/cron.d/max-multiseat



# rescan multiseat devices in a early stage
if [ -x "/etc/init.d/multiseat-rescan" ]; then
	update-rc.d multiseat-rescan start 80 S . >/dev/null
fi


if [ ! -e /etc/X11/default-display-manager ] && [ -e /usr/sbin/gdm ]; then
  echo "/usr/sbin/gdm" > /etc/X11/default-display-manager
fi


#DEBHELPER#
