build/dictionaries/README-es-ES.txt usr/lib/firefox-addons/extensions/es-es@dictionaries.addons.mozilla.org/dictionaries/
build/dictionaries/es-ES.aff        usr/lib/firefox-addons/extensions/es-es@dictionaries.addons.mozilla.org/dictionaries/
build/dictionaries/es-ES.dic        usr/lib/firefox-addons/extensions/es-es@dictionaries.addons.mozilla.org/dictionaries/
build/chrome.manifest     usr/lib/firefox-addons/extensions/es-es@dictionaries.addons.mozilla.org/
build/install.js          usr/lib/firefox-addons/extensions/es-es@dictionaries.addons.mozilla.org/
build/install.rdf         usr/lib/firefox-addons/extensions/es-es@dictionaries.addons.mozilla.org/
firefox-dict-es.js        usr/lib/firefox-3.0/defaults/preferences/
