build/dictionaries/README-es-ES.txt usr/share/firefox-extensions/es-es@dictionaries.addons.mozilla.org/dictionaries/
build/dictionaries/es-ES.aff        usr/share/firefox-extensions/es-es@dictionaries.addons.mozilla.org/dictionaries/
build/dictionaries/es-ES.dic        usr/share/firefox-extensions/es-es@dictionaries.addons.mozilla.org/dictionaries/
build/chrome.manifest     usr/share/firefox-extensions/es-es@dictionaries.addons.mozilla.org/
build/install.js          usr/share/firefox-extensions/es-es@dictionaries.addons.mozilla.org/
build/install.rdf         usr/share/firefox-extensions/es-es@dictionaries.addons.mozilla.org/
