#!/bin/bash


if [ ! -d $HOME/JClic ]; then
  cp -ra /usr/share/jclic/JClic $HOME/
  cat << EOF > $HOME/.edu.xtec.properties
#$(date)
JClic=$HOME/JClic
language=es
EOF
fi

cd $HOME
export JMF_HOME="/usr/lib/jvm/jmf/"
export CLASSPATH="${JMF_HOME}/lib/jmf.jar:${JMF_HOME}/lib/mp3plugin.jar:${JMF_HOME}/lib/mediaplayer.jar:/usr/share/java:${CLASSPATH}"
export LD_LIBRARY_PATH="${JMF_HOME}/lib:${LD_LIBRARY_PATH}"
JAVA=java

ORACLE_JAVA=$(find /usr/lib/jvm/ -maxdepth 1 -type l| grep -v default-java| egrep "(oracle|sun)" | tail -1)
if [ -d "$ORACLE_JAVA" ]; then
    export JAVA_HOME="$ORACLE_JAVA"
    JAVA=${JAVA_HOME}/jre/bin/java
fi


# TCOS thin client
REMOTE_DISPLAY=$(echo $DISPLAY| awk -F ":" '{print $1}')
if [ "${REMOTE_DISPLAY}" != "" ]; then
  if [ -x /usr/bin/padsp ]; then
     padsp -s "$REMOTE_DISPLAY" -n JClic -m JClic-stream $JAVA -cp $CLASSPATH -jar /usr/share/java/jclicreports.jar "$@" 
     exit 0
  fi
fi

$JAVA -cp $CLASSPATH -jar /usr/share/java/jclicreports.jar "$@" 

