#!/usr/bin/python
# -*- coding: UTF-8 -*-
################################################
#
#
#  Allow URL config to be in != localhost
#
#
################################################

import sys

CONFIG="/etc/moodle/config.php"
REPLACES=" $CFG->wwwroot = 'http://'.$_SERVER['SERVER_NAME'].'/moodle';\n"

def getHostname():
    f=open('/etc/hostname', 'r')
    hostname=f.readline()
    f.close()
    return "%s"%hostname.strip()

APACHE="/etc/moodle/apache.conf"
APACHE_ALLOW="allow from 127.0.0.0/255.0.0.0\nallow from 127.0.1.0/255.0.0.0\nallow from %s\n"%(getHostname())


def configure_apache():
    f=open(APACHE, 'r')
    data=f.readlines()
    f.close()

    edit=False

    for i in range(len(data)):
        if not edit and "allow from" in data[i]:
            data[i]=APACHE_ALLOW
            edit=True

        if "# settings" in data[i]:
            # file is edited with maxmoodle-gui
            return

    f=open(APACHE, 'w')
    for line in data:
        f.write(line)
    f.close()

    # link if no exists
    if not os.path.lexists("/etc/apache2/conf.d/moodle.conf"):
        os.symlink(APACHE, "/etc/apache2/conf.d/moodle.conf")


def configure_moodle():
    f=open(CONFIG, 'r')
    data=f.readlines()
    f.close()


    for i in range(len(data)):
        if "$CFG->wwwroot" in data[i]:
            data[i]=REPLACES

        if "?>" in data[i]:
            data[i]="?>"

    f=open(CONFIG, 'w')
    for line in data:
        f.write(line)
    f.close()



configure_moodle()
configure_apache()
#print getHostname()
