#! /bin/bash
 
#if [ -d /boot/efi/ ] ; then 
if [ ! -z $(ls -A /boot/efi) ]; then

EFI_NUM=`efibootmgr | awk '/MAX/ {print $1}' | sed -e 's/Boot//g' -e 's/*//g' | tail -1`

	if ! [ "$EFI_NUM" == "" ] ; then
	efibootmgr -o $EFI_NUM
	fi

fi

