#!/bin/sh

# Looks for opensc.conf
if [ -e "/etc/opensc.conf" ]; then
  openscconf=/etc/opensc.conf
elif [ -e "/etc/opensc/opensc.conf" ]; then
  openscconf=/etc/opensc/opensc.conf
elif [ -e  "/usr/local/etc/opensc.conf" ]; then
  openscconf=/usr/local/etc/opensc.conf
else 
  echo "Could not be able to find out the location of opensc.conf. Please you must configure it manually."
  exit 0
fi

openscconforig=$openscconf".bak.dnie";

# Looks for gnome default.session and default.session.orig
gnome_default="/usr/share/gnome/default.session"
gnome_default_orig=$gnome_default".orig"

# Looks for kde session files
kde_dnie="/usr/share/apps/kconf_update/kdnie.upd"
kde_inst_pkcs11="/usr/share/apps/kconf_update/inst_kde_pkcs11_cert.pl"

if [ "$1" = "remove" ]; then
   # Looks for opensc.conf.orig
   if [ -e $kde_dnie ]; then
      rm $kde_dnie
   fi

   if [ -e $kde_inst_pkcs11 ]; then
      rm $kde_inst_pkcs11
   fi

   echo "DNIe files removed correctly!"
fi

if [ "$1" = "purge" -a -e /usr/share/debconf/confmodule ]; then
  #Remove GNOME SESSION CONFIG

 
   if [ -e $gnome_default ]; then
    /usr/share/opensc/.eliminardefaultdnie
     echo "Recovered GNOME session file"
     if [ -e $gnome_default_orig ]; then
 	rm $gnome_default_orig
     fi  
     
     if [ -e $gnome_default_orig ]; then
       mv $gnome_default_orig $gnome_default
       echo "File default.session.orig deleted "
     fi
   fi



   # Source debconf library.
   
   if [ -f /usr/share/debconf/confmodule ]; then
        . /usr/share/debconf/confmodule
        db_purge
   fi
 
    /usr/bin/perl /usr/share/opensc/.purgednie
    echo "Purged dnie configuration from file opensc.conf."

    rm /usr/share/opensc/.purgednie
    rm /etc/opensc/opensc.conf.bak.dnie

   # Remove OpenSC-DNIe changes to the db.
    
    # Looks for dnie config files
    dnie_files_dir="/usr/share/opensc-dnie"

    if [ -e $dnie_files_dir ]; then
     rm -r $dnie_files_dir
    fi

    # Remove .dnie_lock file from all home directories
    rm /home/*/.dnie_lock

    echo "DNIe files purged correctly!"
fi

if [ "$1" = "remove" ]; then
        ldconfig
fi

