#!/bin/sh
# initramfs hook for max-hardware

case "$1" in
    prereqs)
       exit 0
       ;;
esac

. /usr/share/initramfs-tools/hook-functions


#FIXME
#  check for kopt in grub???
#  grep "# kopt" /boot/grub/menu.lst


# needed utils to copy /usr to ramdisk
copy_exec /usr/bin/rsync /bin
copy_exec /bin/df /bin

