#!/bin/sh
#
# called from /etc/apt/apt.conf.d/92update-dpsyco-skel
#

echo "Procesando disparadores para max ..."

if [ -x /usr/share/gnome-menus/update-gnome-menus-cache ]; then
  LC_ALL=C /usr/share/gnome-menus/update-gnome-menus-cache /usr/share/applications > /usr/share/applications/desktop.C.cache
  LC_ALL=es_ES.UTF-8 /usr/share/gnome-menus/update-gnome-menus-cache /usr/share/applications > /usr/share/applications/desktop.es_ES.utf8.cache
fi

UPDATE_GRUB=0

if ! grep -q "MaX-6.0" /etc/default/grub 2>/dev/null; then
  echo '' >> /etc/default/grub
  echo 'GRUB_DISTRIBUTOR="MaX-6.0"' >> /etc/default/grub
  UPDATE_GRUB=1
fi

if grep -q "^GRUB_HIDDEN" /etc/default/grub 2>/dev/null; then
  sed -i -e 's/^GRUB_HIDDEN/#GRUB_HIDDEN/g' /etc/default/grub
  UPDATE_GRUB=1
fi

# add acpi=force reboot=warm to fix reboot and poweroff issues
if ! grep -q "acpi=force" /etc/default/grub 2>/dev/null; then
  . /etc/default/grub
  echo "# this will fix poweroff and reboot issues in MAX" >> /etc/default/grub
  echo "GRUB_CMDLINE_LINUX=\"$GRUB_CMDLINE_LINUX acpi=force reboot=warm \"" >> /etc/default/grub
  UPDATE_GRUB=1
fi


if [ "$UPDATE_GRUB" = "1" ]; then
  if [ -x "`which update-grub 2>/dev/null`" ] && [ -e /boot/grub/grub.cfg ]; then
      update-grub
  fi
fi

# force to not dist upgrades
if [ -f /etc/update-manager/release-upgrades ]; then
  if ! grep -q "^Prompt=never" /etc/update-manager/release-upgrades 2>/dev/null; then
    echo " * Desactivando actualizaciones a nuevas versiones ..."
    sed -i -s 's/Prompt=.*/Prompt=never/g' /etc/update-manager/release-upgrades
  fi
fi


# delete dropbear hook
if [ -f /usr/share/initramfs-tools/hooks/dropbear ]; then
  rm -f /usr/share/initramfs-tools/hooks/dropbear
  [ -x /usr/sbin/update-initramfs ] && update-initramfs -u
fi



/usr/sbin/update-dpsyco-skel > /dev/null 2>&1 || true
