#!/bin/sh
#
# called from /etc/apt/apt.conf.d/92update-dpsyco-skel
#

echo "Procesando disparadores para max ..."

/usr/sbin/update-dpsyco-skel > /dev/null 2>&1 || true

rm -f /usr/share/applications/Internet/WebHTTrack.desktop  /usr/share/applications/Internet/WebHTTrack-Websites.desktop

[ -e /usr/share/applications/libreoffice-writer.desktop ] && \
[ -e /usr/share/applications/openoffice.org-writer.desktop ] && rm -f /usr/share/applications/openoffice.org*

if [ -x /usr/share/gnome-menus/update-gnome-menus-cache ]; then
  # this breaks Smart PDI install script WTF !!!!
  #LC_ALL=C /usr/share/gnome-menus/update-gnome-menus-cache /usr/share/applications > /usr/share/applications/desktop.C.cache
  rm -f /usr/share/applications/desktop.C.cache
  LC_ALL=es_ES.UTF-8 /usr/share/gnome-menus/update-gnome-menus-cache /usr/share/applications > /usr/share/applications/desktop.es_ES.utf8.cache
fi

UPDATE_GRUB=0

if [ -e /etc/default/grub ]; then
  if ! grep -q "MaX-6.5" /etc/default/grub 2>/dev/null; then
    echo '' >> /etc/default/grub
    echo 'GRUB_DISTRIBUTOR="MaX-6.5"' >> /etc/default/grub
    UPDATE_GRUB=1
  fi

  if grep -q "^GRUB_HIDDEN" /etc/default/grub 2>/dev/null; then
    sed -i -e 's/^GRUB_HIDDEN/#GRUB_HIDDEN/g' /etc/default/grub
    UPDATE_GRUB=1
  fi

  # add acpi=force reboot=warm to fix reboot and poweroff issues
  if ! grep -q "acpi=force" /etc/default/grub 2>/dev/null; then
    . /etc/default/grub
    echo "# this will fix poweroff and reboot issues in MAX" >> /etc/default/grub
    echo "GRUB_CMDLINE_LINUX=\"$GRUB_CMDLINE_LINUX acpi=force reboot=warm \"" >> /etc/default/grub
    UPDATE_GRUB=1
  fi


  if [ "$UPDATE_GRUB" = "1" ]; then
    if [ -x "`which update-grub 2>/dev/null`" ] && [ -e /boot/grub/grub.cfg ]; then
      update-grub
    fi
  fi
fi # end of [ -e /etc/default/grub ]


# force to not dist upgrades
if [ -f /etc/update-manager/release-upgrades ]; then
  if ! grep -q "^Prompt=never" /etc/update-manager/release-upgrades 2>/dev/null; then
    echo " * Desactivando actualizaciones a nuevas versiones ..."
    sed -i -s 's/Prompt=.*/Prompt=never/g' /etc/update-manager/release-upgrades
  fi
fi


# delete dropbear hook
if [ -f /usr/share/initramfs-tools/hooks/dropbear ]; then
  rm -f /usr/share/initramfs-tools/hooks/dropbear
  [ -x /usr/sbin/update-initramfs ] && update-initramfs -u
fi


# configure SSH to not allow danger logins
if [ -f /etc/ssh/sshd_config ]; then
  if ! grep -q "# MAX" /etc/ssh/sshd_config ; then
    cat << EOF >> /etc/ssh/sshd_config

# ******** no borrar este comentario ******
# MAX
# deshabilitar contraseñas conocidas
# para activar el login cambiar la contraseña
# del usuario que se quiera habilitar y eliminar
# su nombre de la siguiente línea
#
#
DenyUsers madrid alumno profesor
EOF
  # restart ssh service
  restart ssh || true
  fi
fi



if [ -d /usr/lib/jvm/ ] && [ -e /usr/share/descartes/DescartesLib.jar ]; then
  # link descartes in every JAVA package
  JVMS=$(find /usr/lib/jvm/ -maxdepth 1 -mindepth 1 -type d | grep -v jmf)
  for jvm in $JVMS; do
    if [ -d ${jvm}/jre/lib/ext/ ] && [ ! -e ${jvm}/jre/lib/ext/DescartesLib.jar ]; then
      ln -s /usr/share/descartes/DescartesLib.jar ${jvm}/jre/lib/ext/
    fi
  done
fi

if [ -x /usr/bin/xdg-mime ] && [ -e /etc/gnome/defaults.list ]; then
  # chech exe-learning mime
  if [ "$(xdg-mime query default application/x-exe-learning 2>/dev/null)" = "" ]; then
    echo "application/x-exe-learning=exe.desktop" >> /etc/gnome/defaults.list
  fi
fi


# update Firefox defaults
FF_DIR=$(dirname /usr/lib/firefox/firefox)
FF_DEF=/usr/share/max-firefox-conf/defaults/profile/
if [ ! -e "$FF_DIR/defaults/profile/localstore.rdf" ]; then
  echo " * Actualizando perfil de Firefox $FF_DIR"
  mkdir -p "$FF_DIR/defaults/profile/"
  cp $FF_DEF/* "$FF_DIR/defaults/profile/"
fi

# clean OLF firefox
for f in $(echo /usr/lib/firefox-*/defaults 2>/dev/null); do
  [ ! -d "$f" ] && continue
  [ -e "$f/../firefox" ] && continue
  echo " * Limpiando versiones viejas de Firefox $f"
  rm -rf "$f"
done

# force install translations (FF12 breaks it)
for t in $(ls /usr/lib/firefox-addons/extensions/*xpi); do
  #echo $t
  tname=$(basename $t)
  if [ ! -e "/usr/lib/firefox/extensions/$tname" ]; then
    ln -s "$t" "/usr/lib/firefox/extensions/$tname"
  fi
done

# force install translations (FF12 breaks it)
for t in $(ls /usr/lib/thunderbird-addons/extensions/*xpi); do
  #echo $t
  tname=$(basename $t)
  if [ ! -e "/usr/lib/thunderbird/extensions/$tname" ]; then
    ln -s "$t" "/usr/lib/thunderbird/extensions/$tname"
  fi
done


if ! grep -q "old-releases" /etc/apt/sources.list ; then
    sed -i.max-backup -e 's@http://*.*.ubuntu.com@http://old-releases.ubuntu.com@g' -e 's@http://*.ubuntu.com@http://old-releases.ubuntu.com@g' /etc/apt/sources.list
    echo " * Por favor ejecuta «sudo apt-get update» para usar old-releases.ubuntu.com"
fi
