etc/X11/Xsession.d/
etc/profile.d/
etc/xdg/autostart/synapse.desktop
usr/lib/max-mate/
usr/share/applications/
usr/share/glib-2.0/schemas/max-mate.gschema.override
usr/share/mate-panel/layouts/
usr/share/mate/applications/defaults.list
usr/share/mate/applications/compiz.desktop
usr/share/mate/applications/debian-uxterm.desktop
usr/share/mate/applications/debian-xterm.desktop
usr/share/mate/applications/display-im6.desktop
usr/share/mate/applications/display-im6.q16.desktop
usr/share/mate/applications/kde-Kantiword-Installer.desktop
usr/share/mate/applications/language-selector.desktop
usr/share/mate/applications/marco.desktop
usr/share/mate/applications/software-properties-gtk.desktop
usr/share/mate/applications/tilda.desktop
usr/share/mate/autostart/
usr/share/plank/themes/

usr/share/max-mate/settings-overlay

usr/share/glib-2.0/schemas/zz-max-mate-plank.gschema.override
usr/share/mate/plank/normal
usr/share/max-mate/settings-overlay
