#!/bin/sh

set -e

case "$1" in
    configure)
	update-flashplugin-nonfree --install --fast || \
	echo "Try again later with \"update-flashplugin-nonfree --install\"."
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0


