#!/bin/sh -e


if test -e /boot/grub/grub.cfg && which update-grub2 > /dev/null ; then
    update-grub2
fi


exit 0

. /usr/share/debconf/confmodule

db_get backharddi-ng/grub-conf
GRUBCONF="$RET"

[ -f $GRUBCONF ] && sed -i "/###INICIO\ SISTEMA\ DE\ BACKUP/,/###FIN\ SISTEMA\ DE\ BACKUP/d" $GRUBCONF || true

db_get backharddi-ng/lilo-conf
LILOCONF="$RET"

[ -f $LILOCONF ] && sed -i "/###INICIO\ SISTEMA\ DE\ BACKUP/,/###FIN\ SISTEMA\ DE\ BACKUP/d" $LILOCONF || true
