#!/bin/sh

set -e

PACKAGE=backharddi-udeb
package=debian/${PACKAGE}/lib/$2

install -d $package/$1

cp -r $1/* $package/$1/

if [ -f $package/$1/_numbers ]; then
    numbers=$(cat $package/$1/_numbers)
    rm $package/$1/_numbers
    echo "$numbers" |
    while read number name; do
	set -e
	mv $package/$1/$name $package/$1/${number}${name}
    done
fi

