#!/bin/sh

# create virtualbox group

case "${1}" in
        configure)
                # Adding vboxusers group
                if ! getent group vboxusers > /dev/null
                then
                        addgroup --quiet --system vboxusers
                fi

	rm -f /usr/share/initramfs-tools/scripts/casper-bottom/14locales.distrib

esac

#DEBHELPER#

exit 0
