#!/bin/sh

set -e

case "$1" in
    configure)
        echo "Update Dpsyco skel..."
        /usr/sbin/update-dpsyco-skel > /dev/null 2>&1

    # create manual launcher in existent HOMES
    for home in /home/*; do
      if [ -d $home/Desktop ] && [ ! -e $home/Desktop/manual.desktop ]; then
         ln -s /etc/skel/Desktop/manual.desktop $home/Desktop/manual.desktop || true
      fi
      if [ -d $home/Escritorio ] && [ ! -e $home/Escritorio/manual.desktop ]; then
         ln -s /etc/skel/Desktop/manual.desktop $home/Desktop/manual.desktop || true
      fi
    done

    ;;

    abort-upgrade|abort-remove|abort-deconfigure)

    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac

exit 0


