#!/bin/sh

set -e

case "$1" in
    configure)
        echo "Update Dpsyco skel..."
        /usr/sbin/update-dpsyco-skel > /dev/null 2>&1

    # create manual launcher in existent HOMES
    for home in /home/*; do
      if [ -d $home/Desktop ] && [ ! -e $home/Desktop/manual.desktop ]; then
         ln -s /etc/skel/Escritorio/manual.desktop $home/Desktop/manual.desktop || true
         chown $(basename $home) $home/Desktop/manual.desktop || true
      fi
      if [ -d $home/Escritorio ] && [ ! -e $home/Escritorio/manual.desktop ]; then
         ln -s /etc/skel/Escritorio/manual.desktop $home/Escritorio/manual.desktop || true
         chown $(basename $home) $home/Escritorio/manual.desktop || true
      fi
    done
    ;;

esac

#DEBHELPER#


exit 0


