#!/bin/sh

set -e

case "$1" in
    configure)
        /usr/sbin/update-dpsyco-skel

    # create manual launcher in existent HOMES
    for home in /home/*; do
      if [ ! -e $home/Desktop/manual.desktop ]; then
         ln -s /etc/skel/Desktop/manual.desktop $home/Desktop/manual.desktop || true
      fi
    done

    ;;

    abort-upgrade|abort-remove|abort-deconfigure)

    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac

exit 0


