#!/bin/sh

set -e

case "$1" in
       purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
       echo "Update Dpsyco skel..."
       /usr/sbin/update-dpsyco-skel > /dev/null 2>&1

    # delete manual launcher in existent HOMES
    for home in /home/*; do
      if [ -e $home/Desktop/manual.desktop ]; then
         rm -f $home/Desktop/manual.desktop
      fi
      if [ -e $home/Escritorio/manual.desktop ]; then
         rm -f $home/Escritorio/manual.desktop
      fi
    done


        ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 0

esac

exit 0


