#!/bin/sh

set -e

case "$1" in
  purge)
    # delete manual launcher in existent HOMES
    for home in /home/*; do
      if [ -e $home/Desktop/manual.desktop ]; then
         rm -f $home/Desktop/manual.desktop
      fi
      if [ -e $home/Escritorio/manual.desktop ]; then
         rm -f $home/Escritorio/manual.desktop
      fi
    done
    ;;

esac

#DEBHELPER#


exit 0


