#!/bin/sh

set -e

case "$1" in
       purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
       echo "Update Dpsyco skel..."
       /usr/sbin/update-dpsyco-skel > /dev/null 2>&1

        ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 0

esac

exit 0


