#!/bin/sh

set -e

case "$1" in
    configure)
        echo "Update Dpsyco skel..."
        /usr/sbin/update-dpsyco-skel > /dev/null 2>&1


    ;;

    abort-upgrade|abort-remove|abort-deconfigure)

    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac

exit 0


