#!/bin/sh

set -e

case "$1" in
    configure)
        echo "Updating Dpsyco skel..."
        /usr/sbin/update-dpsyco-skel > /dev/null 2>&1

        echo "Call maxmenus"
	/usr/sbin/maxmenus --update >> /tmp/maxmenus.log 2>&1


    ;;

esac


#DEBHELPER#

exit 0


