.TH acroread 1 "May 2009" acroread "Linux User's Manual"
.SH NAME
acroread - Adobe PDF Viewer for viewing PDF files on X Window System.

.SH SYNOPSIS
.B acroread
[\fIOPTIONS\fR] [\fIfile\fR]

.SH DESCRIPTION
\fBAdobe Reader\fR is a free PDF reader, designed for
standards compliance, performance and portability. It is a tool for opening and using Adobe PDFs that are created in Adobe Acrobat. Although you can't create PDFs in Reader, you can use Reader to view, print, and manage PDFs. After opening a PDF in Reader, you have a variety of tools to help you find information quickly. If you receive a PDF form, you can complete it online and submit it electronically. If you receive an invitation to review a PDF, use the commenting and markup tools to annotate it. Use the Reader multimedia tools to play video and music in a PDF. And if a PDF contains sensitive information, you can sign or certify a document with a digital ID.

.SH OPTIONS
A summary of the options supported by \fBacroread\fR is included below.

.SS "acroread options"
.TP
.BI \-\-display= DISPLAY
X display to use
.TP
.BI \-\-screen= SCREEN
X screen to use. Use this options to override the screen part of the DISPLAY environment variable.
.TP
.B \--sync
Make X calls synchronous
.TP
.B \-h, \-help
Prints the common command-line options.
.TP
\fB\-geometry\fR \fIwidth\fRx\fIheight\fR
Set height of startup window to \fIvalue\fR.
.TP
.B \-v, \-version
Print \fBacroread\fR version.
.TP
.B \-iconic
Launches in an iconic state on the desktop.
.TP
.B \-setenv\fR \fIvar\fR=\fIvalue\fR
Tells the main application to perform the equivalent of C-shell setenv \fIvar\fR \fIvalue\fR.
.TP
\fB\-tempFile\fR
Indicates files listed on the command line are temporary files and should not be put in the recent file list.
The document title will be the title in the pdf document, instead of the filename.
.TP
\fB\-tempFileTitle\fR \fItitle\fR
Same as -tempFile, except the title is specified.
.TP
.B \-openInNewInstance\fR
It launches a new instance of acroread process. The application starts normally without checking if it is already running.
.TP
.B \-openInNewWindow\fR
Same as OpenInNewInstance. But it is recommended to use OpenInNewInstance. openInNewWindow will be deprecated.
.TP
.B \-installCertificate <server-ip> <server-port>\fR
Fetches and installs client-side certificates for authentication to access the server while creating secured connections.
.TP
.B \-installCertificate [-PEM|-DER] <PathName>\fR
Installs the certificate in the specified format from the given path to the Adobe Reader Certificate repository.

.TP
.B /a\fR
Switch used to pass the file open parameters. To use more than one file open parameter, use & as the separator and the options should be within quotes. See the example below:
.br
acroread /a "page=NUM & zoom=NUM" PDF_FILE.pdf
.RS
\fBnameddest=name\fR - Specifies a named destination in the PDF.
.br
\fBpage=pagenum\fR - Specifies a numbered page in the document, using an integer value.
.br
\fBzoom=scale\fR - Sets the zoom and scroll factors, using float or integer
values.
.br
\fBzoom=scale,left,top\fR - Scroll values left and top are in a coordinate system where 0,0 is the top left of the visible page, regardless of document rotation.
.br
\fBview=<option>\fR - Set the view of the displayed page, using keyword values defined in the PDF Language Specification. Scroll values left and top are floats or integers in a coordinate system where 0,0 is the top left of the visible page, regardless of document rotation. Use the page command before this command.
.br
\fBview=Fit\fR 
.br
\fBview=FitH\fR
.br
\fBview=FitH,top\fR
.br
\fBview=FitV\fR
.br
\fBview=FitV,left\fR
.br
\fBview=FitB\fR
.br
\fBview=FitBH\fR
.br
\fBview=FitBH,top\fR
.br
\fBview=FitBV\fR
.br
\fBview=FitBV,left\fR
.br
\fBviewrect=left,top,wd,ht\fR - Sets the view rectangle using float or integer values in a coordinate system where 0,0 is the top left of the visible page, regardless of document rotation. Use the page command before this command.
.br
\fBpagemode=<option>\fR - Displays bookmarks or thumbnails.
.br
\fBpagemode=bookmarks\fR
.br
\fBpagemode=thumbs\fR
.br
\fBpagemode=none (default)\fR
.br
\fBscrollbar=1|0\fR - Turns scrollbars on or off.
.br
\fBsearch=wordList\fR - Opens the Search UI and performs a search for the specified word list in the document. Found words are highlighted in the document. The words must be enclosed in quotes and separated by spaces; for example: #search="word1 word2"
.br
\fBtoolbar=1|0\fR - Turns the toolbar on or off.
.br
\fBhighlight=lt,rt,top,btm\fR - Highlights a specified rectangle on the displayed page. (Use the page command before this command.) The rectangle values are integers in a coordinate system where 0,0 is the top left of the visible page, regardless of document rotation.
.br
\fBhelp=index\|contents\|search\fR - Used only when opening a file from the command line or an Apple Event. Opens the document in the Help window, with the specified navigation panel selected.
.RE

.TP
.B \-toPostScript\fR \fIoptions\fR \fIpdf-file\fR ... \fIps-dir\fR
.TP
.B \-toPostScript\fR \fIoptions\fR \fI\-pairs\fR \fIpdf-file1\fR \fIps-file1\fR ...
.TP
.B \-toPostScript \fIoptions\fR
Converts the given pdf_files to PostScript.

In the first form, if the last file specified is a directory, then all preceding files will be converted to PostScript and the generated PostScript files will be placed into ps-dir.
If a directory is not specified, then the PostScript files will be placed in the same directory as the original file.

In the second form, the file list contains pairs, each consisting of a PDF filename and a corresponding PostScript filename.

The third form specifies a filter, reading a PDF file from standard input and writing the PostScript file to standardoutput.

Note: When using \fB\-toPostScript\fR it must be the first argument passed in on the command line.

The following are valid options for the conversion of PDF to PostScript:
.RS
\fB\-printerName\fR <name> - this is to print device-dependent PS.
.br
\fB\-rotateAndCenter\fR- auto-rotate and center the pages.
.br
\fB\-choosePaperByPDFPageSize\fR- use the pdf page size to determine the output tray.
.br
\fB\-nUp\fR- <hpage> <vpage> <pageorder> border rotate - print multiple pages on the same sheet of paper.
.br
	\fRhpage,vpage:\fR can take numbers upto 99.
.br
	\fRpageorder:\fR how the pages are ordered on paper. Possible page orders are:
.br
	0 (Horizontal)
.br
	1 (HorizontalReversed)
.br
	2 (Vertical)
.br
	3 (VerticalReversed)
.br
	\fRborder:\fR draws the crop-box of PDF pages
.br
	\fRrotate:\fR automatically rotates each page
.br
\fB\-booklet\fR <subset> <binding> rotate <from> <to> - prints multiple pages on the same sheet of paper in the order required to read correctly when folded.
.br
	\fR subset:\fR determines which side of the paper print. Possible options are :
.br
	0 (PrintBothSides)
.br
	1 (PrintFrontSideOnly)
.br
	2 (PrintBackSideOnly)
.br
	\fRfrom,to:\fR specifies the first and last sheet to print.
.br
	\fRrotate:\fR automatically rotates each page.
.br
	\fRbinding:\fR determines the orientation for the binding. Possible options are:
.br
	0 (BookletBinding_Left)
.br
	1 (BookletBinding_Right)
.br
	2 (BookletBinding_LeftTall)
.br
	3 (BookletBinding_RightTall)
.br
\fB\-binary\fR - emit binary PostScript where possible
.br
\fB\-start\fR \fIint\fR - identify the first page in the document to be converted (default is the first page of the document)
.br
\fB-end\fR \fIint\fR - identify the last page in the document to be converted (default is the last page of the document)
.br
\fB-optimizeForSpeed\fR - emit PostScript such that all fonts are emitted once at the beginning of the document.  This results in faster transmission times and smaller PostScript documents but requires more PostScript printer virtual memory.
.br
\fB\-landscape\fR - rotate the pages to print landscape
.br
\fB\-reverse\fR - reverse the page order of the output
.br
\fB\-odd\fR - emit only odd-numbered pages
.br
\fB\-even\fR - emit only even-numbered pages
.br
\fB\-commentsOff\fR - don't print comments
.br
\fB\-annotsOff\fR - don't print annots
.br
\fB\-stampsOff\fR - don't print stamps
.br
\fB\-markupsOn\fR - print document and markups
.br
\fB\-level2\fR - emit Level 2 PostScript  (level1 is not supported)
.br
\fB\-level3\fR - emit Level 3 PostScript
.br
\fB\-printerhalftones\fR - use the printer default halftones.
.br
\fB\-saveVM\fR - download fonts as needed to preserve printer memory
.br
\fB\-scale\fR <int>\fR - scale the pages according to the scale factor (default is 100 percent)
.br
\fB\-shrink\fR - shrink the pages to fit the page size
.br
\fB\-expand\fR - expand the pages to fit the page size
.br
\fB\-size\fR <pagesize> - set the page size.  The following page sizes are recognized:
.br
	letter - letter size paper
.br
	tabloid - tabloid size paper
.br
	ledger - ledger size paper
.br
	legal - legal size paper
.br
	executive - executive size paper
.br
	a3 - ISO standard A3 size
.br
	a4 - ISO standard A4 size
.br
	a5 - ISO standard A5 size
.br
	b4 - ISO standard B4 size
.br
	b5 - ISO standard B5 size
.br
	wxh - custom size paper where w is the integer width in points and h is the integer height in points
.br
\fB\-transQuality\fR \fIlevel\fR - set the transparency flattening level Value from 1-5, where 1 means rasterize everything, 5 means rasterize as little as possible, default is 3.
.RE
.RS
.TP
.B Mutually exclusive options
The following are the mutually exclusive print options, their usage together can lead to undesired results:
.br
	1. expand, shrink, nUp and booklet
.br
	2. annotsOff, commentsOff, markupsOn and stampsOff
.br
	3. landscape and choosePaperByPDFPageSize

.SH ENVIRONMENT VARIABLES
ACRO_DISABLE_FONT_CONFIG : Set this if you donot want Adobe Reader to cache Font-config fonts.

.SH VERSION
9.1.0

.SH AUTHORS
This program was written by \fBAdobe Systems Incorporated\fR   \fIhttp://www.adobe.com\fR.
