#!/bin/sh
#
# Copyright © 2008-2009, Christian Marillat <marillat@debian.org>
# All Rights Reserved
#

if [ ! -d $HOME/.adobe ]; then
  cp -ra /usr/share/acroread-debian-files/adobe $HOME/.adobe
  ln -s /usr/lib/Adobe/Reader8/Reader/Cert/curl-ca-bundle.crt $HOME/.adobe/Acrobat/8.0/Cert/curl-ca-bundle.crt
fi


if [ -f /usr/lib/Adobe/Reader8/Reader/intellinux/bin/acroread ]; then
	READER=Reader8
	# For mozilla-acroread package
	ver="8.1.7"
elif [ -f /usr/lib/Adobe/Reader9/Reader/intellinux/bin/acroread ]; then
	READER=Reader9
	# For mozilla-acroread package
	ver="9.3"
fi

if [ -z "$ver" ]; then
	echo "Can't find a valid acroread installation."
	exit 1
fi

if [ "$1" = "-version" ]; then
  echo "$ver"
  exit
fi

# See /etc/locale.gen for language locale

case "$LANG" in
    de_*)
	ACRO_EXEC_CMD=/usr/lib/Adobe/$READER/bin/acroread-deu
	ACRO_LANG="DEU"
	ERRMSG="Install the acroread-l10n-de package if you want acroread in German."
	;;
    es_*)
	ACRO_EXEC_CMD=/usr/lib/Adobe/$READER/bin/acroread-esp
	ACRO_LANG="ESP"
	ERRMSG="Install the acroread-l10n-es package if you want acroread in Spanish."
	;;
    fr_*)
	ACRO_EXEC_CMD=/usr/lib/Adobe/$READER/bin/acroread-fra
	ACRO_LANG="FRA"
	ERRMSG="Installez le paquet acroread-l10n-fr si vous voulez avoir acroread en Français."
	;;
    it_*)
	ACRO_EXEC_CMD=/usr/lib/Adobe/$READER/bin/acroread-ita
	ACRO_LANG="ITA"
	ERRMSG="Install the acroread-l10n-it package if you want acroread in Italian."
	;;
    ja_*)
	ACRO_EXEC_CMD=/usr/lib/Adobe/$READER/bin/acroread-jpn
	ACRO_LANG="JPN"
	ERRMSG="Install the acroread-l10n-ja package if you want acroread in Japanese."
	;;
    ko_*)
	ACRO_EXEC_CMD=/usr/lib/Adobe/$READER/bin/acroread-kor
	ACRO_LANG="KOR"
	ERRMSG="Install the acroread-l10n-ko package if you want acroread in Korean."
	;;
    pt_BR)
	ACRO_EXEC_CMD=/usr/lib/Adobe/$READER/bin/acroread-ptb
	ACRO_LANG="PTB"
	ERRMSG="Install the acroread-l10n-pt-br package if you want acroread in Brazilian."
	;;
    *)
	ACRO_EXEC_CMD=/usr/lib/Adobe/$READER/bin/acroread-en
	ACRO_LANG="ENU"
	ERRMSG="No executable found"
esac

if [ ! -x "$ACRO_EXEC_CMD" ]; then
    echo "$ERRMSG" >&2
    ACRO_EXEC_CMD=/usr/lib/Adobe/$READER/bin/acroread-en
    ACRO_LANG="ENU"
fi

export ACRO_LANG

$ACRO_EXEC_CMD ${1+"$@"}
