#!/bin/sh



if [ "$1" = "configure" ]; then

   [ -x /usr/lib/lightdm/lightdm-set-defaults ] &&  /usr/lib/lightdm/lightdm-set-defaults --hide-users || true

   [ -e /etc/init.d/max-ldap ] && rm -f /etc/init.d/max-ldap


    if [ -f /etc/ldap.conf ] && [ "$(grep -c ^rootbinddn /etc/ldap.conf)" != "0" ]; then
      # disable rootbinddn
      sed -i -e 's/rootbinddn/#rootbinddn/g' /etc/ldap.conf
      rm -f /etc/ldap.secret
    fi


    if ! grep -q "# max-ldap" /etc/ssh/sshd_config; then
        cat << EOF >> /etc/ssh/sshd_config

# max-ldap
# Al estar este equipo unido al dominio,
# sólo se permite el acceso a usuarios del grupo 'Instaladores'
# (perfil Administrador en max-control)
# no pueden acceder ni usuarios locales, ni profesores ni Coordinadores TIC

AllowGroups Instaladores
EOF
        restart ssh || true
    fi


    # add gdm-2.20 to pam groups
    #gdm;*;*;Al0000-2400;audio,video,floppy,cdrom,plugdev,netdev,powerdev,scanner,fuse
    #gdm-2.20;*;*;Al0000-2400;audio,video,floppy,cdrom,plugdev,netdev,powerdev,scanner,fuse
    if ! grep -q "^gdm-2.20" /etc/security/group.conf; then
        echo "gdm-2.20;*;*;Al0000-2400;audio,video,floppy,cdrom,fuse" >> /etc/security/group.conf
    fi

    if [ -d /etc/gdm/PostSession/ ]; then
    # ensure to umount $HOME in GDM Postlogin
    if ! grep -q umount /etc/gdm/PostSession/Default; then
        cat << EOF > /etc/gdm/PostSession/Default
#!/bin/sh

id | grep -q "__USERS__" || exit 0

sleep 1
umount "/home/samba/users/\$USER/.gvfs"
sleep 1
umount "/home/samba/users/\$USER"
exit 0
EOF

    fi
    fi


    if [ -d /etc/lightdm/ ]; then
       cp /usr/share/max-ldap/script_logout.sh /etc/lightdm/
       chmod +x /etc/lightdm/script_logout.sh
       if ! grep -q "session-cleanup-script=/etc/lightdm/script_logout.sh" /etc/lightdm/lightdm.conf ; then
          echo session-cleanup-script=/etc/lightdm/script_logout.sh >> /etc/lightdm/lightdm.conf
       fi
    fi


fi


exit 0
