#!/bin/bash

#
#  Configurar servicios netboot de max-server
#
#

#
# Configurar TCOS
#

if [ -f /etc/tcos/tcos.conf ]; then
  . /etc/tcos/tcos.conf
  echo " * Configurando NET-menu TCOS ... "
   sed -e "s/__TCOS_KERNEL__/${TCOS_KERNEL}/g" \
    /var/lib/max-netboot/pxelinux.cfg/tcos.menu.tpl > /var/lib/max-netboot/pxelinux.cfg/tcos.menu


  # configurar XFS
  if [ $(grep -c "^no-listen" /etc/X11/fs/config) != 0 ]; then
    sed -i 's/no-listen/#no-listen/g' /etc/X11/fs/config
    invoke-rc.d xfs restart
  fi


  # generar imagenes de arranque
  if [ -x /usr/sbin/gentcos ]; then
    # cachear paquetes
    PKGS="esound libesd0 discover libdiscover2 discover-data"
    if [ -d /cdrom/pool/max ]; then
      for pkg in $PKGS; do
         abspkg=$(find /cdrom/pool/max -name "${pkg}_*")
         echo "Cacheando $pkg en /var/cache/tcos/packages/${pkg}"
         rm -rf /var/cache/tcos/packages/${pkg} ; mkdir -p /var/cache/tcos/packages/${pkg}
         dpkg --extract ${abspkg} /var/cache/tcos/packages/${pkg}
      done
    else
      gentcos -instpkg $PKGS
    fi
    # generar imagenes de arranque 
    gentcos -tftp
  fi
fi

#
# Configurar Backharddi
#

if [ -d /usr/share/backharddi ]; then
  # buscar kernel
  BK_KERNEL=$(basename `ls /boot/linux*backharddi*`)
  BK_INITRD=$(basename `ls /boot/minirt*backharddi*`)
  echo " * Configurando NET-menu Backharddi ... "
  sed -e "s/__BK_KERNEL__/${BK_KERNEL}/g" \
       -e "s/__BK_INITRD__/${BK_INITRD}/" \
    /var/lib/max-netboot/pxelinux.cfg/backharddi.menu.tpl > /var/lib/max-netboot/pxelinux.cfg/backharddi.menu
fi

#
# Configurar servidor DHCP
#
# FIXME
