#!/bin/bash -e

. ./toolchain/shared

BUILDDIR=../$BUILDDIR
#En el entorno de bitten el paquete fuente se descarga en el directorio "src"
mv src $SRC
cd $SRC
BUILDEROPTS="--buildplace $BUILDDIR/build --hookdir $BUILDDIR/hooks"
DEBBUILDOPTS="$([ $ARCH = i386 ] && echo "-b" || echo "-B")"
PDEBUILDOPTS="--pbuilderroot $ROOTCMD --buildsourceroot fakeroot --pbuilder $BUILDER --buildresult $BUILDDIR/result/$BRANCH/$DIST --debbuildopts $DEBBUILDOPTS" 
echo "Construyendo paquete $SRC de la rama $BRANCH para la distribución $DIST $ARCH"
install -d $BUILDDIR/result/$BRANCH/$DIST
pdebuild $PDEBUILDOPTS -- $BUILDEROPTS --distribution $DIST --aptcache $BUILDDIR/aptcache/$DIST $BUILDERBASE $BUILDDIR/$DIST.$ARCH.$BUILDEREXT --mirror $MIRROR --components "main universe"
mv ../${SRC}_* $BUILDDIR/result/$BRANCH/$DIST
