#!/bin/bash -e

export HOME=/root
DIST=$1
SRC=$(basename $2)
BRANCH=${2%%/$SRC}
DEST=../builder/result/$BRANCH/$DIST
NETRC=$HOME/.netrc
CONFIGFILE=/etc/max-bitten-slave
USERNAME=$(grep ^username $CONFIGFILE | cut -d= -f 2 | tr -d " ")

[ ! -f $NETRC ] || mv $NETRC ${NETRC}.bak
cat > $NETRC <<EOT
machine max.educa.madrid.org
login $USERNAME
passwd $(grep ^password $CONFIGFILE | cut -d= -f 2 | tr -d " ")
EOT
chmod 600 $NETRC
for file in $(cat $DEST/${SRC}_*.changes | egrep "^\ [0123456789abcdef]{32}\ " | cut -d " " -f 6) $DEST/${SRC}_*.changes; do
	cadaver http://max.educa.madrid.org:8000/incoming <<EOT
mkdir $BRANCH
cd $BRANCH
lcd $DEST
mput $file
EOT
	rm $DEST/$file
done
rm $DEST/${SRC}_*.changes
rm $DEST/${SRC}_*.build
[ -f ${NETRC}.bak ] && mv ${NETRC}.bak $NETRC || rm $NETRC
